### ISSUE TITLE
UI-UX CoP Meeting Agendas 2022 (Wednesday 6PM PST)

### ISSUE THREAD

**Issue by bradyse** [hackforla/UI-UX#276]
### Overview
This issue tracks the agenda for the UI-UX CoP meetings.

### Weekly Agenda, Recordings, and Meeting Notes
- October 2022 [2022-10-26](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1292831980) [2022-10-19](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1284757365)
- September 2022 [2022-09-28](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1260078480) [2022-09-21](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1260077342) [2022-09-14](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1242763676) [2022-09-07](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1240387235)
- August 2022 [2022-08-31](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1233616073) [2022-08-17](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1219027209) [2022-08-10](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1212681881)
- July 2022: [2022-07-13](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1183910456) [2022-07-20](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1190378244)
- June 2022: [2022-06-29](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1170639474) [2022-06-01](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1150595029) [2022-06-08](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1150601022)
- May 2022: [2022-05-11](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1124453237) [2022-05-18](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1130971652)
- April 2022: [2022-04-13](https://github.com/hackforla/UI-UX/issues/276#issuecomment-1098644581)

### Resources/Instructions

- [Zoom link for Wednesday meetings](https://us02web.zoom.us/j/81630670134?pwd=RTNLRHlBSE1DeXRudkJJMHkzZGlVUT09)
- [Google Drive UI/UX CoP folder](https://drive.google.com/drive/folders/1Bw4qy9rQtJ16ccYsRUIg5BlxBxlqnEIQ?usp=sharing)
- [Old UI-UX CoP Agenda Issue](https://github.com/hackforla/UI-UX/issues/41)

#### Template for Slack Channel Announcements
<details>
<summary>Slack channel template - Replace emojis and info as needed</summary>
:sparkle: **This Week's UI/UX Community of Practice!** :sparkle:

:bulb:**What?** [REPLACE]
:watch:**When?** [REPLACE]
:computer:**Where?** [REPLACE]
:trophy:**Why?** [REPLACE]

:meow_bread_appear: **Need the Zoom link?** If you have been onboarded to Hack for LA already and you deleted the CoP meeting link, add your email to this thread to let us know to add you to the invite. If you have questions, at message one of the UI/UX CoP Leads!

UI/UX CoP Leads
@Julia Gab 
@Aparna Gopal 
@Sara Brady 
</details>

#### Template for Meeting Agenda
Copy and paste code below:
```

## YYYY-MM-DD Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)
```

**Comment by bradyse** [comment]
## 2022-04-13 Meeting Agenda

### Prework to prep for meeting

### Recurring items:

- [ ] Introductions for new members
- [ ] Review items in Progress

### New Items

- [ ] Discuss UI-UX CoP direction
- [ ] Discuss need for UI-UX CoP Co-Leads

### FYIs

- Fill out survey from onboarding on Slack
- Complete Experience Profile: Slide 29 from Onboarding; make sure that on GitHub, make sure that you set up your experience profile. It serves to keep track of people but also document all of your skills. 


### Meeting Notes
#### Attendees:

- [ ] Maria Elizabeth Rodriguez Beltran
- [ ] Sara Brady
- [ ] Aubrey Schiavone 
- [ ] Soyoung Park
- [ ] Mariana Melo-Vega
- [ ] Julia Gab
- [ ] Nayely B.
- [ ] Nikita Shah
- [ ] Josef ‘Jay’
- [ ] Matt Steecker
- [ ] John Huang
- [ ] Eevin Jennings
- [ ] Jasiah Jaylo
- [ ] Serena Sanders

#### Introductions
- **Maria Elizabeth Rodriguez Beltran** – UI/UX Co-lead
- **Sara Brady** – background in experimental psychology
- **Aubrey Schiavone** – current Assistant Prof with expertise in qualitative research
- **Soyoung Park** – From Korea, interested in quantitative methods, but also open to doing interviews
- **Mariana Melo-Vega** – former prof in Latin American studies, interested in working on projects
- **Julia Gab** – Romanian heritage but moved from Spain; went through bootcamp via Design Lab, worked with kids and animals
- **Nayely B.** – Interested in research, bachelor’s degree in anthropology
- **Nikita Shah** – Located in Washington, D.C., graduated with master’s in clinical psychology, here to learn the language and build skills, work with interdisciplinary teams
- **Josef ‘Jay’** – Finished bootcamp at UCLA, here to learn more about UI
- **Matt Steecker** – From upstate NY; transitioning from career as local journalist; did Google career cert in UX design; hoping to branch out into UI design
- **John Huang** – Located in Vancouver, background in multimedia design, wanted to focus on UX/UI part
- **Eevin Jennings** – Lecturer at ASU; teach cognition and neuroscience; found that usability testing had overlap with UX research
- **Jasiah Jaylo** – Did bootcamp a few years ago and had an apprenticeship pre-pandemic, but currently trying to get back into UI/UX, looking for community, and new ideas/projects
- **Serena Sanders** – Background is in music copyright and music publishing; did UX bootcamp, looking for opportunities for working on a team and have experience working with different disciplines

#### Future of UI-UX CoP

- Interested in professional development workshops, guest speakers, breakout groups for portfolio review
- We need to move stuff from old Google Drive to new Google Drive
- We need to update guide, handbook, etc.
- We need to create a table on GitHub that keeps track of people in CoP
- We need to keep good records of who was working on what so that if people leave the organization, there is a record of what was done and next steps
- We need to have leads create breakout groups in onboarding sessions
- Leads will invite other people to come talk to the CoP
- If we share an idea, we need to know how to execute it.

**Plug for CoP Co-Lead**
- Opportunity to demonstrate leadership skills
- Networking


#### Questions
_How to see all the projects?_

- hackforla/UI-UX
- Click on Projects
- Look for open roles
- Click on all open roles, because sometimes roles are cross-listed within projects

_What is the highest priority?_
- Moving the drive files from the old files to new files

_What are the qualifications of Co-Lead?_ 
- No expertise, but it is extra on top of the projects

_What is our timeline into choosing a project?_
- No exact timeline; but probably within the next couple weeks.

_What is the timeline for CoP meetings?_
- No meeting the first week of each month
- Every week we meet otherwise
- There is a time commitment.

**Comment by bradyse** [comment]
## 2022-05-11 Meeting Agenda

### Prework to prep for meeting
N/A

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] Google Drive migration: Need to update spreadsheet with owners of files

### New Items 
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

#### Google Drive Info
Google has "Shared Drives" where the drive itself owns the files and Google has a recovery process. Everyone has their own drive in their own email address. 

Sometimes, you have people create their own folders with shared files. HfLA moved to the new model to where everyone can add shared files to a drive as long as they have permission.

We can't copy the files without the OWNER moving the file to the new drive. We need to invite

#### Joining a Team
Notes from Bonnie regarding assessing people with UX Research skills upon onboarding:

User Researcher and Research Lead

Statements
I feel comfortable :

Taking work and breaking it into smaller tasks so that multiple people can work on it
Organizing and Leading meetings
Googling examples when I don't have the answer
Reviewing content/examples from other teams (when provided) to replace a successful process
Creating Guidance for others after I have learned how to do something myself
Communicating on behalf of others (team representative)
Giving constructive feedback to teammates
Work collaboratively with multiple people in a meeting
Providing an overview to a new team member

I know what the following things are:
personas
interviews
surveys
user testing of mockups
usability testing of working product
Qualitative Analysis
Quantitative Analysis
Accessibility standards

#### Where to Find Research Guides
- Go to Guides Tracker: https://github.com/orgs/hackforla/projects/3
- Type "Research" into the search guide
- Look around and see what boards each issue is attached to
- Some guides are in varying level of progress or abandonment.


### Tasks

#### Inviting Guests to Speak to UI/UX group
- Ask Jane He from the TDM team to come speak to UI/UX as a successful research lead
- Simone Campbell from HfLA Website team speak about auditing research; how do you audit research once a team has already done research?

#### For CoP Leads:
- When logging into Zoom meeting:
- Go to HfLA Zoom Three
- Go to Meetings
- Claim Host in participant's tab 
- Put host key's tab in there.

### Items for next week's agenda

**Comment by bradyse** [comment]
> 

@ExperimentsInHonesty see this issue: https://github.com/hackforla/UI-UX/issues/292

**Comment by bradyse** [comment]
## 2022-05-18 Meeting Agenda

### Prework to prep for meeting
N/A

### FYIs 
N/A

### Recurring items: 
 - Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - Join a Team: https://github.com/hackforla/UI-UX/projects/2


### New Items 
#### [UI/UX Guides](https://github.com/hackforla/UI-UX/projects/1)
 - New people to CoP should be picking up a guide
 - [CoP Presentation to Find a Guide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_37)
 - [Resources on Finding a Guide](https://github.com/hackforla/guides/wiki/Guide-Resources)
 - Guide-Resources shows instructions on how to work with Guides (Where to start) is where to start.
   - Ice Box - should be made into separate issues (e.g., How to use Figma Mirror, etc.). These need to be made into issues so that people can pick them up as guides.
 - Walking through an example
   - Create a Guide: Comparative & Competitive Analysis (Complexity: good first issue)
   - C&C sheet - those are the ones that have competitive analysis; guidance for writing a guide
   - Next step is to follow the instructions. 
   - Assign yourself the issue.

#### Join a Team
 - Go [UI/UX Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - Ask team for **onboarding document**
   - Guidance on how to join that team; what they've done so far, etc.
   - It should be on a Wiki page or in a Google doc
   - It should _not_ be the entire drive (the team should have more specific documentation)

### Notes from meeting
 - Bonnie went through and demonstrated how to find a guide to work on.
 - Aparna asked about Design Systems and asking people with that expertise to come and speak. Bonnie suggested that people go and talk with people working on different projects to learn from others.
 - Bonnie walked us through Figma (e.g., HfLA website); pages show previous versions and red box indicates current version. You can see whole history from original wireframes to now. Communicating that if you're going to use Figma, that you should use the methodology for how to use Figma. 
 - Sara reminded people to work on their research profiles
 - Yating asked about how to join a team.
 - Sara and Aparna shared info on the Access the Data team

### Tasks

#### For CoP Leads:
 - Ideas for future CoP meetings
   - Portfolio workshop (do you need them?)
   - What is a good research project to walk through for an interview?
   - Have people from every project to discuss what they're doing.

### Items for next week's agenda

**Comment by Aparna1Gopal** [comment]
@bradyse Thank you for the notes! Made a small edit to this section

Tasks- For CoP Leads:
 FROM.. What is a good research project to walk through for an interview? 
TO.. 
 What is a good research/design project to walk through for an interview?
(To reflect our overall UI/UX Community)

**Comment by Aparna1Gopal** [comment]
2022-05-18 Meeting Agenda

Prework to prep for meeting

N/A

FYIs

N/A

Recurring items:

Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
Join a Team: https://github.com/hackforla/UI-UX/projects/2
New Items

[UI/UX Guides](https://github.com/hackforla/UI-UX/projects/1)

New people to CoP should be picking up a guide
[CoP Presentation to Find a Guide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_37)
[Resources on Finding a Guide](https://github.com/hackforla/guides/wiki/Guide-Resources)
Guide-Resources shows instructions on how to work with Guides (Where to start) is where to start.
Ice Box - should be made into separate issues (e.g., How to use Figma Mirror, etc.). These need to be made into issues so that people can pick them up as guides.
Walking through an example
Create a Guide: Comparative & Competitive Analysis (Complexity: good first issue)
C&C sheet - those are the ones that have competitive analysis; guidance for writing a guide
Next step is to follow the instructions.
Assign yourself the issue.
Join a Team

Go [UI/UX Open Roles](https://github.com/hackforla/UI-UX/projects/2)
Ask team for onboarding document
Guidance on how to join that team; what they've done so far, etc.
It should be on a Wiki page or in a Google doc
It should not be the entire drive (the team should have more specific documentation)
Notes from meeting

Bonnie went through and demonstrated how to find a guide to work on.
Aparna asked about Design Systems and asking people with that expertise to come and speak. Bonnie suggested that people go and talk with people working on different projects to learn from others.
Bonnie walked us through Figma (e.g., HfLA website); pages show previous versions and red box indicates current version. You can see whole history from original wireframes to now. Communicating that if you're going to use Figma, that you should use the methodology for how to use Figma.
Sara reminded people to work on their research profiles
Yating asked about how to join a team.
Sara and Aparna shared info on the Access the Data team
Tasks

For CoP Leads:

Ideas for future CoP meetings
Portfolio workshop (do you need them?)
What is a good research/design project to walk through for an interview?
Have people from every project to discuss what they're doing.
Items for next week's agenda

**Comment by bradyse** [comment]
## 2022-06-01 Meeting Agenda (Guest Speaker: Simon Wolfe Taylor)

### Prework to prep for meeting
N/A

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items:
- [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
- [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
- [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/2
- [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/3

### New Items

### Notes from meeting
[Link to Recording, Notes, and Slides](https://docs.google.com/presentation/d/1uVnPf9eFXpZxoxslXxtn9TeJDQbGgIonjepfoj7FkOI/edit?usp=sharing)

### Tasks

### Items for next week's agenda

**Comment by bradyse** [comment]
## 2022-06-08 Meeting Agenda

### Prework to prep for meeting
N/A

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items:
- [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
- [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
- [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/2
- [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/3

### New Items
N/A

### Notes from meeting
#### Attendees:

- [ ] Paul Bahle
- [ ] Sara Brady
- [ ] Julia Gab
- [ ] Sandarsh Pandey
- [ ] Angela Darosh
- [ ] Mano Sakayan
- [ ] Van (Trang) Pham
- [ ] Bonnie Wolfe

#### Notes:
- Informal meeting no planned agenda
- We shared who recently joined a project and what that was like
- Went over how to update labels on UI/UX Research Guides
- Shared next steps in terms of guest speakers

### Tasks
@bradyse needs to check on Google Calendar CoP invite for Anita Morales and Angela Darosh

### Items for next week's agenda
- Jane He is scheduled to speak June 22 to CoP group

**Comment by bradyse** [comment]
## 2022-06-29 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A
> 
### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/2
- [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

**Comment by bradyse** [comment]
## 2022-07-13 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting
Guest speaker: Danielle N.
Role: UX Design
16 attendees


### Tasks
 

### Items for next week's agenda
- Natalia V. to share logo designs for UI/UX CoP YouTube Channel

**Comment by bradyse** [comment]
## 2022-07-20 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 
**Upcoming Dates:**
- August 3: No meeting - planning week
- August 24: Panel Discussion with Maria Elizabeth B. and Eevin J.
 
### Notes from meeting



### Tasks
 CoP Lead post-meeting: https://github.com/hackforla/UI-UX/issues/244

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by Aparna1Gopal** [comment]
**2022-08-10 Meeting Agenda**

Prework to prep for meeting

N/A

FYIs

N/A

Recurring items:

Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
Join a Team: https://github.com/hackforla/UI-UX/projects/2
New Items

[UI/UX Guides](https://github.com/hackforla/UI-UX/projects/1)
[documentation](https://github.com/hackforla/UI-UX/labels/documentation) 
https://github.com/orgs/hackforla/projects/3
Video for finding UX guides and templates https://github.com/hackforla/UI-UX/issues/292

New people to CoP should be picking up a guide
[CoP Presentation to Find a Guide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_37)
[Resources on Finding a Guide](https://github.com/hackforla/guides/wiki/Guide-Resources)

Guide-Resources shows instructions on how to work with Guides (Where to start) is where to start.
Ice Box - should be made into separate issues (e.g., How to use Figma Mirror, etc.). These need to be made into issues so that people can pick them up as guides.
Walking through an example
Create a Guide: Comparative & Competitive Analysis (Complexity: good first issue)
C&C sheet - those are the ones that have competitive analysis; guidance for writing a guide
Next step is to follow the instructions.
Assign yourself the issue.
Join a Team
Go [UI/UX Open Roles](https://github.com/hackforla/UI-UX/projects/2)

Ask team for onboarding document
Guidance on how to join that team; what they've done so far, etc.
It should be on a Wiki page or in a Google doc
It should not be the entire drive (the team should have more specific documentation)
Notes from meeting

We had a general open discussion session co-led by Aparna G and Maria E
Responded to common questions by community members: including joining projects, working on projects, how to select a guide/project, working on only one project a time, working on one project & one guide at a time such that it can function as two case studies during job interviews, and other overarching topics.
Discussed transition stories from peers and their pathway into UX/UI Research and Design. This helped map out career journeys for other peers in the group, and set out priorities for their individual career journeys.
Discussed resources including articles/podcasts/readings/guides etc. that UX'ers could use as they transition from a different field, utilizing the peer network at HfLA, networking and connecting on LinkedIn
Having a guest speaker Simone Wolfe coming in next week (June 1) for a talk at the CoP meeting (identify topics for discussion during talk)
For CoP Leads:

Ideas for future CoP meetings

Portfolios (Both Design and Research, differences/similarities, do you need them, process etc.)
Process of Interviewing
How to show Impact and translate Impact from your previous jobs into your current UI/UX role
Negotiating a job offer (pay/benefits etc.)

**Comment by Aparna1Gopal** [comment]
## 2022-07-20 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 
**New CoP co-Leads:**
- Adrienne D.
- Julia G.

**Upcoming Dates:**
- August 3: No meeting - planning week
- August 24: Panel Discussion with Maria Elizabeth B. and Eevin J.
 
### Notes from meeting
Attendees and Introductions:
- Karen M.
- Sara B.
- Julia G.
- Adrienne D.
- Vanessa M.
- Natalia V.
- Shima H.
- Jolleen O.
- Justin Y.
- Neha S.
- Koyel R.
- Brittany A.

New to HfLA
- Using GitHub
- Google Drive

UI/UX CoP Logo Presentation by Natalia

### Tasks
 CoP Lead post-meeting: https://github.com/hackforla/UI-UX/issues/244

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-08-17 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting

- Check out open roles board for openings.
- If you're interested in UXR roles, contact Internship or Website team leads for joining those two projects who can take excess researchers
- Bonnie gave her stage rehearsal talk about harnessing the power of Kanban
- Feedback was great
- Announcement for next week: Maria Elizabeth B. and Eevin J. are coming back to give a talk as panelists.


### Tasks
 

### Items for next week's agenda
- Contact Maria Elizabeth B. and Eevin J. about confirming next week's talk.

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-08-31 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-09-14 Meeting Agenda
 
### Prework to prep for meeting
- [ ] Collect questions for guest speaker Maria
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-09-14 Meeting Agenda
 
### Prework to prep for meeting
- [ ] Create document that catalogs list of interview questions.
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 
- Interview Workshop

 
### Notes from meeting
- Aparna greeted newcomers and relayed how to find open roles.
- We then created a document that people could use to choose interview questions from during the breakout groups.
- We created two breakout rooms (one for UI/UX design and one for UX Research).

#### Resources shared
- [Guide for Getting Started as a UX Researcher](https://www.userresearchacademy.com/user-research-blog/getting-started-as-a-user-research-a-comprehensive-guide?fbclid=IwAR0EWCJDO3wN_z1zZmMnoRTOyuAZdqUK-V81Gcg_SwUfgYqu1w9LQ-rLtA4)
- [Learning UXR Lingo](https://bootcamp.uxdesign.cc/business-acumen-for-the-ux-researcher-7453dbbdae14)
- [HfLA UI/UX CoP Google Drive with Interview Resources](https://drive.google.com/drive/folders/1d6e8NN19VS3u3Z8KO_695D9BvpdWbbjs?usp=sharing)



### Tasks
- [ ] Create interview guide with HfLA Branding
- [ ] Confirm Maze Designers are coming at 11 am PST next Wed
 

### Items for next week's agenda
- Maze Guest Speakers- NOTE THE TIME CHANGE

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-09-28 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-10-12 Meeting Agenda
 
### Prework to prep for meeting
- [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
- [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 
- [ ] Introduce new members
- [ ] Share guide creation updates
- [ ] Answer questions about joining a team
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-10-19 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by bradyse** [comment]
## 2022-10-26 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by Aparna1Gopal** [comment]
## 2022-11-09 Meeting Agenda
 
### Prework to prep for meeting
Consent from Briel K to record talk by in-house speaker
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 
Yas, PM of Design Systems will be giving a 10-minute presentation to the UI/UX Community regarding the Design systems Figma KIT

### Notes from meeting
- Yas, PM of Design Systems gave a 10-minute presentation on HfLA's Design systems Figma KIT

- Briel K gave a 20-30 presentation/talk on the value of creating Guides, Briel's own experiences on working for a guide at HfLA, Benefits of guide creation, Ways to leverage this guide creation experience in UI/UX portfolios for job searching/interviewing

### Tasks

Aparna G Updated UI/UX CoP Wiki with details shared during Yas' & Briel's talks 
Accessed here: https://github.com/hackforla/UI-UX/wiki

UI/UX CoP taking a break during late November & December 
Will be working on Co-lead tasks discussed under New Items here: https://github.com/hackforla/UI-UX/issues/187#issuecomment-1298077116

### Items for next week's agenda
- Interview Workshop

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by juliagab56** [comment]
Closing this 2022 issue. Please reference new 2023 issue [https://github.com/hackforla/UI-UX/issues/396](url)
