### ISSUE TITLE
UI/UX CoP Co-Leads Guidelines (Leadership Checklist doc)

### ISSUE THREAD

**Issue by Eevinjennings** [hackforla/UI-UX#280]
### Overview
I volunteered to clarify, validate, and organize the content in the CoP Leadership Checklist for more intuitive and accurate information. I am leaving comments in the Google Doc and running/noting analyses in a separate doc, which I will link when finished. I will update in comments here as I go. I am collaborating with @MariaElizabeth04. 

### Action Items
- [ ] Identify what is unclear from the outset.
- [ ] Check link validity.
- [ ] Analyze the following:
  - [ ] Style
  - [ ] Consistency
  - [ ] Grammar
  - [ ] Punctuation
  - [ ] Lexicon
  - [ ] Redundancy
  - [ ] Structure
  - [ ] Transitions
  - [ ] Homonyms
  - [ ] Diction
- [ ] Accessibility analysis:
  - [ ] Pronoun use
  - [ ] Sensory
  - [ ] Pacing
  - [ ] Readability
  - [ ] Lexical diversity
- [ ] Fix/propose fixes to identified issues in separate document.

### Resources/Instructions
[Working UI/UX CoP Doc](https://docs.google.com/document/d/16_21FvtE_j4F6jOfVd7a1sLLAaEFhzPI9UvK_GiGEkI/edit?usp=sharing)
[Original UI/UX CoP Doc](https://docs.google.com/document/d/1aFnPCY9PS8dXpOikM4yNSvCXyZF5XUQWTNPGldJ5dio/edit#)
[Editing Tool (private bc of premium subscription)](https://app.prowritingaid.com/?id=MwWzeRYVJy)
