### ISSUE TITLE
UI-UX CoP Meeting Agendas 2023 (Wednesday 6PM PST)

### ISSUE THREAD

**Issue by juliagab56** [hackforla/UI-UX#396]
### Overview
This issue tracks the agenda for the weekly UI-UX CoP meetings.

### Weekly Agenda, Recordings, and Meeting Notes
[August 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1700439874)
[July 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1633722190)
[June 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1592172754)
[May 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1543616206)
[April 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1506166467)
[March 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1462293082)
[February 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1423885063)
[January 2023](https://github.com/hackforla/UI-UX/issues/396#issuecomment-1379947876)

### Resources/Instructions

- [Zoom link for Wednesday meetings](https://us02web.zoom.us/j/81630670134?pwd=RTNLRHlBSE1DeXRudkJJMHkzZGlVUT09)
- [Google Drive UI/UX CoP folder](https://drive.google.com/drive/folders/1Bw4qy9rQtJ16ccYsRUIg5BlxBxlqnEIQ?usp=sharing)
- [2022 UI-UX CoP Agenda Issue](https://github.com/hackforla/UI-UX/issues/276)
- [UI/UX Cop Lead / Org Agenda](https://github.com/hackforla/UI-UX/issues/187)
- [Instructions for Google Calendar Invite](https://github.com/hackforla/UI-UX/issues/187#issuecomment-1368171521)

#### Template for Slack Channel Announcements
<details>
<summary>Slack channel template - Replace emojis and info as needed</summary>
:sparkle: **This Week's UI/UX Community of Practice!** :sparkle:

:bulb:**What?** [REPLACE]
:watch:**When?** [REPLACE]
:computer:**Where?** [REPLACE]
:trophy:**Why?** [REPLACE]

:meow_bread_appear: **Need the Zoom link?** If you have been onboarded to Hack for LA already and you deleted the CoP meeting link, add your email to this thread to let us know to add you to the invite. If you have questions, at message one of the UI/UX CoP Leads!

UI/UX CoP Leads
@Julia Gab 
@Aparna Gopal 
@Sara Brady 
</details>

#### Template for Meeting Agenda
Copy and paste code below:
```

## YYYY-MM-DD Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)
```

**Comment by Aparna1Gopal** [comment]
## YYYY-MM-DD Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] Getting Started at HfLA UI/UX: https://github.com/hackforla/UI-UX
 - [ ] Set up Research Profile: https://github.com/hackforla/UI-UX/projects/5
 - [ ] UI/UX Research Open Roles: https://github.com/hackforla/UI-UX/projects/2
 - [ ] UI/UX Design Open Roles: https://github.com/hackforla/UI-UX/projects/3


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/276#issue-1203955700)

**Comment by Aparna1Gopal** [comment]
## YYYY-MM-DD Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile[(https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## YYYY-MM-DD Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-02-09 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
None
 
### Notes from meeting
- Total 12-15 members attended 
- Conducted general open office to troubleshoot & streamline new members. 
- Also had updates on regular veteran members of the UI/UX CoP. Shared updates on new roles commenced at HfLA, their experience reaching out for open roles on the GitHub board. 
- Shared mentorship platforms & resources 
- Interest for Portfolio Workshops. Planning to conduct portfolio workshops in the upcoming weeks. 
- Interest shown by a member in PM roles in addition to UX Design. Directed member to the PM CoP. 
- Spoke about the advantages of GitHub profile also working as an online portfolio to document workflows etc. especially for PMs. 
- Discussed guides & selection process of guides/ importance of working on guides/its use & advantage as a portfolio piece. 
- One member has been working on a guide. Had some questions. We had the member screen share & collectively worked on troubleshooting. 
- Also touched on the topic of keeping great documentation within HfLA - both for personal tracking of workflow & also to keep the workflow going seamlessly without any blockers (irrespective of members being on a project or out). Keeping a continuous workflow. 


### Tasks
 Update Wiki with resources shared during UI/UX CoP meeting 
Helen Lin's (guest speaker) talk/recording has been uploaded to the UIUX Drive. Verify & update Wiki, accordingly. 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-02-15 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Bonnie was the meeting for about 10 minutes & introduced a new project required for Onboarding. User Interviews to be conducted at next Onboarding with new members. To identify user experiences during/post onboarding. 
 
### Notes from meeting
- Had open office hours 
- Members discussed questions from guides they are currently working on 
- Discussed projects & guides for new members
- Discussed the new User Interview Onboarding project recently introduced. Recruited potential UX Researcher introduced in working on the project 

### Tasks
 

### Items for next week's agenda
Work on activity for open office hours next week
Prep for the new UX Research Onboarding project

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-02-22 Meeting Agenda
 
### Prework to prep for meeting
Activity 
-Jennifer N worked on the slide deck & put together/designed the networking [activity] (https://docs.google.com/presentation/d/1grfhnC2uTE8-AkJLEF_eLCYe5RiLvVIleOIXtWc-8dQ/edit#slide=id.p)
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [x] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [x] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [x] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [x] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [x] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [x] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
N/A
 
### Notes from meeting
- Had Networking Activity 
- Recruited UXRs to work on Onboarding project 

### Tasks
Prep for Onboarding UXR Project 

### Items for next week's agenda
- Prep for the new UX Research Onboarding project
- Workshops/meetings planned by Co-Leads this week & the next to prep the UXRs for the Onboarding Project https://github.com/hackforla/UI-UX/issues/420 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by juliagab56** [comment]
## 2023-03-08 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
N/A
 
### Notes from meeting
- Evan presented his guide and got feedback from the team
- Bonnie and Ying showed up at the last 15 minutes to talk about UXR resources and templates from the TWE project


### Tasks
 - Book Ying to speak at next CoP meeting
 - Ask if Evan and Inbal to come back and talk about their guides

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-03-15 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
N/A
 
### Notes from meeting

- Bonnie visited during first 5-10 minutes. Spoke about guest speakers, knowledge transfer from TWE Project, Onboarding project (to analyse surveys first & then explore interviews method)
- Evan discussed next steps on guide presented last week
- Inbal discussed guide currently working on & next steps 

### Tasks
 - Book Ying to speak at next CoP meeting
 - Ask if Evan and Inbal to come back and talk about their guides

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-03-22 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
[Generate Training Modules - 2023-03-22 & 2023-04-12: Sara B & Ying O / TWE Project, Best Practices ](https://github.com/hackforla/UI-UX/issues/427)

### Notes from meeting
Had Sara B & Ying O from TWE Project for a training/workshop on best practices. This workshop will serve as training modules Org wise. 


### Tasks
- Required to log into Zoom 3 account to record talk and Q&A
- Recorded Talk 
- Update on Wiki once recording is available


### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by bradyse** [comment]
## 2023-04-12 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-04-19 Meeting Agenda
 
### Prework to prep for meeting

- Create FigJam Board for SGD Workshop.
- Co-Leads Jennifer & Aparna met on April 18,2023 - 6-7:30PM to brainstorm & create this FigJam Board. 

 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
https://github.com/hackforla/UI-UX/issues/457
https://github.com/hackforla/UI-UX/issues/458

### Notes from meeting
- Bonnie stopped by the UI/UX CoP to discussed open UX Research role at the Guides Project. 
- Bonnie also discussed feedback & next steps with the available Onboarding Team members. Video recording available. Contact Onboarding Team for video recording.  
- The Participatory Design/Participatory Action Workshop for the SGDs was conducted with the community https://github.com/hackforla/UI-UX/issues/457

### Tasks
- Analyse data from the SDG Workshop. Make a short presentation to walkthrough at the next all-Leads meeting in early May. 

### Items for next week's agenda
https://github.com/hackforla/UI-UX/issues/428

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-05-10 Meeting Agenda
 
### Prework to prep for meeting

- Prep GitHub Issue with all collated questions within the UI/UX CoP for mock interview practice

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
https://github.com/hackforla/UI-UX/issues/464

### Notes from meeting
- Used a round table- revolving door to ask each other interview questions & provide feedback on interviewing style & responses
- Only one UI/UX CoP Co-Lead is currently available, thus keeping the activities in such a manner that it can be managed by one Co-Lead. 

### Tasks
- Create GitHub Issue for next week's Interview Prep Workshop: UX Whiteboard Challenges  

### Items for next week's agenda
Workshop: UX Whiteboard Challenge

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-05-17 Meeting Agenda
 
### Prework to prep for meeting

- Prep GitHub Issue with relevant resources for mock UX Whiteboard Challenges 

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
https://github.com/hackforla/UI-UX/issues/465

### Notes from meeting
- Used these [Instructions](https://github.com/hackforla/UI-UX/issues/465#issuecomment-1549050550) to conduct the UX Whiteboard Challenges
- Only one UI/UX CoP Co-Lead is currently available, thus keeping the activities in such a manner that it can be managed by one Co-Lead.

### Tasks
- Create GitHub Issue for next week's Interview Prep Workshop: UX Whiteboard Challenges  

### Items for next week's agenda
Workshop: UX Portfolios & Case Studies for job interviews 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-05-24 Meeting Agenda
 
### Prework to prep for meeting

- Prep GitHub Issue with relevant resources for UX Portfolio / Case Study Presentation Prep

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
#467

### Notes from meeting
https://github.com/hackforla/UI-UX/issues/467#issuecomment-1562164226

### Tasks
- Create GitHub Issue for next week's UX Portfolio / Case Study Presentation Prep

### Items for next week's agenda
Workshop: UX Portfolios & Case Studies for job interviews 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-05-31 Meeting Agenda
 
### Prework to prep for meeting

- Prep for Workshop: UX Portfolios & Case Studies for job interviews (PART 2 continued)
- Prep for Voting of UI/UX CoP Branding

### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
#467

### Notes from meeting
- Shared the voting ballot for the UI/UX CoP Branding 
https://docs.google.com/forms/d/e/1FAIpQLScLhvB8NbgLSVk24E2K9-u1u4lkE7a-YILzQO_NmHxUrbR7zw/viewform

- Completed the Case Study Workshop with the group 
https://github.com/hackforla/UI-UX/issues/467#issuecomment-1571266614


### Tasks
- Start prep for Focus group activity with the UI/UX CoP - for Branding/logo  

### Items for next week's agenda
- All Leads meeting next week. No UI/UX CoP meeting next week. 


---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by bradyse** [comment]
## 2023-06-14 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- [ ] Workshop on Issue Templates
 
### Notes from meeting



### Tasks
 - [ ] Go to UI/UX Issues
 - [ ] Select `Guest Speaker Consent` template
 - [ ] Use the following keywords for the issue
       - Year: `2020` 
       - Name of Guest Speaker: `TEST Mickey Mouse`
       - Month Day of Talk: `July 8`

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-07-19 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)

### New Items 
- [ ] https://github.com/hackforla/UI-UX/issues/470
 
### Notes from meeting
- [ ] https://github.com/hackforla/UI-UX/issues/474

### Tasks
- Prep for next Guest Speaker 
  - [ ] Zoom Webinar 
  - [ ] Consent Forms
  - [ ] Send community questions to guest speaker

### Items for next week's agenda
- [ ] https://github.com/hackforla/UI-UX/issues/470

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by nguyen-jenn** [comment]
## 2023-07-26 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)

### New Items 
N/A
 
### Notes from meeting

- Had office hours for new members (including going over role opportunities)
- Held an icebreaker activity on Figjam
- Number of attendees (Total:14 - including 11 audience members, 3 Co-Leads)

### Tasks
N/A

### Items for next week's agenda
N/A

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
## 2023-08-30 Meeting Agenda
 
### Prework to prep for meeting
- Create Mock Interview Workshop GitHub Issue with collated Interview questions 
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)

### New Items 
N/A
 
### Notes from meeting
- Introduced new Co-lead, Peter G to the community. 
- Conducted the Workshop. [Details here](Workshop: UX Mock Interview Prep (August 2023))
- Last 15 min, conducted office hours for the new members. Shared the UI/UX Wiki & the open guides 


### Tasks
N/A

### Items for next week's agenda
N/A

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/396)

**Comment by Aparna1Gopal** [comment]
- New Agenda Issue being opened for 2024 : UI/UX CoP Meeting Agendas 2024 (Wednesday 6PM PST) #540
- This 2023 Agenda issue is being closed
