### ISSUE TITLE
Onboarding Project: Weekly Meeting Agenda

### ISSUE THREAD

**Issue by InbalRL** [hackforla/UI-UX#432]
### Overview
This issue tracks the agenda and notes for the UI/UX Cop Leads and Org meeting

### Action Items
- [ ] Add the Date of the next meeting below
- [ ] Link the Agenda/Notes from meeting

#### Template
```
## [DATE] Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] Accountability and Support Check.
 - [ ] Review assignments for each Lead and team member

### New Items 
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

### Tasks

### Items for next week's agenda
```

#### Prior and upcoming meetings
[2023-03-23](https://github.com/hackforla/UI-UX/issues/432#issuecomment-1478902981)
[2023-03-31](https://github.com/hackforla/UI-UX/issues/432#issuecomment-1487501910)

**Comment by InbalRL** [comment]
## 2023-03-23 Meeting Agenda

### Prework to prep for meeting

- [ ] Go over HfLA[ Kanban guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit#heading=h.nl3p4nf4eqb4)
- [ ] resources for analyzing survey data
[Analyzing qualitative data](https://www.youtube.com/watch?v=oPNR_g4c-tk) 
[Analyzing quantitative data](https://uk.sagepub.com/sites/default/files/upm-binaries/67702_Kent,_Analysing_Quantitive_Data_Chapter_2.pdf) 

### FYIs (nothing needs to be done, just keeping each other informed)

- [ ] Present current Github issues to the team, go through them, and assign people
- [ ] Creating research plan
- [ ] Discuss best practices for analyzing survey data ([TWE RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews) is good for survey analysis)
- [ ] Create survey analysis slide deck for the team? 
- [ ] Creating [Wiki](https://github.com/hackforla/UI-UX/projects/8#card-88585543) for the Onboarding Project 

### Recurring items: 
 - [ ] Accountability and Support Check
 - [ ] Review assignments for each Lead and team member

### New Items 
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

### Tasks

### Items for next week's agenda

**Comment by InbalRL** [comment]
### 2023-03-31 Meeting Agenda

## Prework to prep for meeting

## FYIs (nothing needs to be done, just keeping each other informed)

- [ ]  Go over the research plan before turning to Bonnie
- [ ]  Go over survey data analysis

## Recurring items:

- [ ]  Accountability and Support Check
- [ ]  Review assignments for each team member

## New Items
add issue numbers to be discussed and any notes that will be helpful

## Notes from meeting

## Tasks

## Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-04-07 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)

- [ ]  Go over survey data analysis (Kevin & Brian)

### Recurring items

- [ ]  Accountability and Support Check
- [ ]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-04-14 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [ ]  Announcement : New member (@chakratal)
- [ ]  Go over survey data analysis

### Recurring items

- [ ]  Accountability and Support Check
- [ ]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-04-21 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [ ]  Discuss next steps based on the feedback provided by Bonnie during [this week's CoP meeting](https://app.slack.com/client/T04502KQX/C04502L0P/files/F0545JD3HKN)

### Recurring items

- [ ]  Accountability and Support Check
- [ ]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-05-05 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [ ]  Take a look at all the roadmaps done by the Internship's project

### Recurring items

- [ ]  Accountability and Support Check
- [ ]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

- Based on our understanding, the idea is that once we finalize the roadmap, we send it to Bonnie to get her feedback and see if she is ok with it. If that's the case, and then after each research plan, she will check with the roadmap to see if it fits (of course the roadmap is iterative so there might be some changes over time)
- Next onboarding session is next Monday (May 8th) so there a possibility that a product manager might come but either way, we can work on the roadmap asynchronously for the time being in order to move forward with this project
- We can think about additional research plans that we can add to the roadmap (Bonnie dropped some ideas during [UI/UX CoP meeting (April 19th)](https://drive.google.com/file/d/1hhuaAVps8YVMY0gLuHdzLN877xz3ptC6/view?usp=share_link)
- Brian will be in vacation 2 weeks in June

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-05-12 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [x]  Work on [our roadmap](https://docs.google.com/document/d/1LIRYyG0KL0Qyw0G5eExWuXd9XuYSVjfE-oj0chKsxSk/edit#)

### Recurring items

- [x]  Accountability and Support Check
- [x]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

- We went over the roadmap, reviewed the comments and made changes when necessary

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-05-19 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [x]  Work on [our roadmap](https://docs.google.com/document/d/1LIRYyG0KL0Qyw0G5eExWuXd9XuYSVjfE-oj0chKsxSk/edit#)

### Recurring items

- [x]  Accountability and Support Check
- [x]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

- We went over the roadmap, reviewed the comments and made changes when necessary

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-05-26 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [x]  Work on [our roadmap](https://docs.google.com/document/d/1LIRYyG0KL0Qyw0G5eExWuXd9XuYSVjfE-oj0chKsxSk/edit#)

### Recurring items

- [x]  Accountability and Support Check
- [x]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

- We went over the roadmap, reviewed the comments and made changes when necessary
- In our roadmap, we proposed to include a research plan (RP004) where we would improve the current onboarding survey by testing its validity and remove/change some questions (when it's needed)
- Everyone will review one last time before sending our roadmap to Bonnie
- Explain to @Yeslindy about our project and answer her questions

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-06-09 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)
- [x]  Think about how we can structure our Wiki (by using [the Wiki of the Internship project](https://github.com/hackforla/internship/wiki) as a reference).

### Recurring items

- [x]  Accountability and Support Check
- [x]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

- Bonnie is off in June 
- Having a heavy interest in the improvement of the HfLA onboarding process and this project, @mxajPrice (the PM on Access the Data and co-lead the Engineering CoP) joined our meeting
- Kevin presented the draft he has done about how we could structure the Wiki 
- aj provided some advice (e.g. don't need to spend too much time on the Wiki, it's a living thing, it's a work in progress)
- Kevin will put the work done with the Wiki structure and put it in [a GitHub issue](https://github.com/hackforla/UI-UX/issues/431)
- Kevin suggested to use milestone to track progress in our project but @mxajPrice said to use it only it makes sense (it will need to be discussed with our PM, @Yeslindy)
- aj discussed about the issues with the CoP Engineering (not enough senior engineers vs. lots of juniors, make the onboarding easier and more efficient)
- @StephanieRoncone and @sallyjyang joined the team, respectively as a Co-Lead UX Researcher and UX Researcher
- No meeting next week

### Tasks

### Items for next week's agenda

**Comment by kevinmoutoucarpin** [comment]
## 2023-08-05 Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)

- July 13 : Karen said that Bonnie and she reviewed the Reach Bonnie form and Bonnie mentioned that due to some more pressing priorities (off boarding Hack for LA from Code for America) Bonnie had to deprioritize a few things such as this project. Karen will be seeing Bonnie this Saturday and will see if this can be reprioritized or if not, how Bonnie can help us all move forward.
- July 18 : Bonnie said that the team should first work on creating a presentation with the summary and recommendations based on the responses from onboarding survey because she wants to understand what came of this work and then she would be more ready to chat about our new research (i.e. our research roadmap). By the way, no need to do the research plan, we can directly jump into the analysis. 

### Recurring items

- [x]  Accountability and Support Check
- [x]  Review assignments for each team member

### New Items
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

- Kevin summarized where we are in the project and what the next steps are
- Kevin showed the analysis he started doing on the questions 16 & 17 (see [Data Analysis Matrix](https://docs.google.com/spreadsheets/d/1ZcMgfCYlMyMJULSdYpRRWk8j9hL4Youj_8N92Ic_Afo/edit#gid=1997160119))
- Kevin answered some questions about the project to @StephanieRoncone & @ngadoq 
- Next meeting will be on August 25th

### Tasks

### Items for next week's agenda

**Comment by Aparna1Gopal** [comment]
### NOTES
- Due to limited resources currently at the UI/UX Community of Practice (CoP), this project has been transferred to a different Community of Practice (as per discussion during All-Leads meeting in March 2024). 
**Observation & Audit:** 
- The UI/UX CoP works primarily as an activity based CoP with no take-home issues/assignments set-up 
All activities are conducted weekly during the UI/UX CoP meetings in real-time and worked on collaboratively as a group
- However, this Onboarding project is more suited to a project-based CoP (wherein there are regular open issues for the CoP members to work on & it is expected that CoP members are assigned to these issues & work on them in their own time - similar to a project). 
- Thus, for an activity based CoP like the UI/UX CoP, this project-type ‘Onboarding Project’ is NOT a suitable fit. 
- Unless there can be a dedicated Co-Lead who can also function as a UX Research Lead, a project of this type can then be housed within the UI/UX CoP. This Co-Lead must have lesser or nil UI/UX CoP Co-Lead duties and more Lead UX Research duties. This Lead UX Researcher should be housed within the UI/UX CoP (under In-House CoP Projects).
- Something to keep in mind before the UI/UX CoP commits to any projects in the future. To weigh the pros & cons of any future projects and primarily identifying if it can work within the activity-based set-up of the UI/UX Community of Practice. 
- All associated open issues related to this project are being closed. 
- Archiving uxr-onboarding-project Slack Channel - Reaching out to admin regarding the same.
