### ISSUE TITLE
UIUX Design Systems Project: Meeting Agenda

### ISSUE THREAD

**Issue by nguyen-jenn** [hackforla/UI-UX#452]
### Overview
This issue tracks the agenda and notes for the UI/UX Design Systems Team.

### Action Items
- [ ] Add the Date of the next meeting below
- [ ] Link the Agenda/Notes from meeting

#### Template
```
## [DATE] Meeting Agenda

### Prework to prep for meeting

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)

### New Items 
add issue numbers to be discussed and any notes that will be helpful

### Notes from meeting

### Tasks

### Items for next week's agenda
```

#### Prior and upcoming meetings
[03/30/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1490718872)
[04/13/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1507586317)
[04/27/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1526613705)
[05/25/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1563504268)
[07/06/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1624294874)
[07/20/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1644744781)
[08/03/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1664788338)
[08/24/23](https://github.com/hackforla/UI-UX/issues/452#issuecomment-1692351088)

**Comment by nguyen-jenn** [comment]
## [04/13/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting

- [ ]  Contact admin regarding a Figma file for the team. 
- [ ]  Reach out to TWE and receive permissions to access their brand book PDF found on their [wiki](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

### FYIs (nothing needs to be done, just keeping each other informed)

N/A

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)

### New Items 

N/A

### Notes from meeting

- Jennifer went over the project overview and main issue in detail 

### Tasks

- Assignment of duties:
      - Colors Research: Yrenia
      - Typography Research: Vivian
- Jennifer: Work on giving access to figma file

### Items for next agenda

- Keep brainstorming logos

**Comment by nguyen-jenn** [comment]
## [04/27/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting

- [x]  Work on logo sketches.
- [x]  Set up Figma file.

### FYIs (nothing needs to be done, just keeping each other informed)

- Assignments:
      - Colors: Yrenia
      - Typography: Vivian
- Personality of UIUX CoP: creative, professional

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [UIUX CoP Design Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)

### New Items 

- [Logo Sketches](https://drive.google.com/drive/u/1/folders/18rHltFqpRIV7dmWK4kSN-eqPVjjb1kCd)

### Notes from meeting

- Rough timeline:
      - Complete line art of clean logos by next meeting: May 25th @ 2pm
      - Create a presentation to present at an upcoming UIUX CoP weekly meeting (Jennifer to discuss with Aparna)
      - Open voting for 2-3 weeks

### Tasks

- Line out logo sketches on Figma
      - Yrenia: Pencil, Double Diamond, Infinity loop
      - Vivian: Heart, Hexagon

### Items for next agenda

- Create presentation slides with the logo sketches & make a voting poll

**Comment by nguyen-jenn** [comment]
## [05/25/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting

- [x]  Finalize logo sketches.

### FYIs (nothing needs to be done, just keeping each other informed)

- Assignments:
      - Colors: Yrenia
      - Typography: Vivian
- Personality of UIUX CoP: creative, professional

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [UIUX CoP Design Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)
 - [Logo Sketches](https://drive.google.com/drive/u/1/folders/18rHltFqpRIV7dmWK4kSN-eqPVjjb1kCd)

### New Items 

N/A

### Notes from meeting

- Rough timeline:
      - May 25th @ 2pm: Complete line art of clean logos
      - May 25th @ 2pm: Create slides to present at an upcoming UIUX CoP weekly meeting (Jennifer to discuss with Aparna). Create a voting form on Google forms.
       - May 31st to June 28th: Opening logo voting to Community
              - May 31st @ 6pm (?): Present slides and opening voting to CoP at weekly meeting
              - May 31st @ 7pm: First publicity Slack message
              - June 14th: Second publicity Slack message + invite community to next weekly meeting for focus group
              - June 21st @ 6pm: Research Focus Group during CoP weekly meeting
              - June 22th or 29th: Compile Research data/Maybe create slides to present findings to CoP if time allows
              - June 28th: Last call publicity Slack message

### Tasks

-

### Items for next agenda

-

**Comment by nguyen-jenn** [comment]
## [07/06/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting

- [ ] Jenn: set up Figjam for Affinity Mapping.

### FYIs (nothing needs to be done, just keeping each other informed)

- Assignments:
      - Colors: Yrenia
      - Typography: Vivian
- Brand Book: [example from TWE](https://github.com/hackforla/internship/wiki/Internship-Brand-Book). Consists of tagline, mission, personality, attributes, values.
- Design Process Overview: [example from TWE](https://github.com/hackforla/internship/wiki/Design-Process-Overview). For our purposes, prioritize brand book, color palette, typography, logo & lastly google slides. If time allows, create email signature, header for forms, color for forms, document templates, spreadsheet templates 

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [Branding/Design Systems 2023 Google Drive](https://drive.google.com/drive/folders/1Va4ExU39N65-vYZAObrq8vBDXyspDYvc?usp=drive_link)
 - [UIUX CoP Design Systems Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)

### New Items 

- [Branding Roadmap](https://github.com/hackforla/UI-UX/issues/472)
- [Research Roadmap](https://github.com/hackforla/UI-UX/issues/473)

### Notes from meeting

Rough Timeline:
- July 6th @ 2pm: Compile research data. Follow up on logo voting.
      - Data Analysis: Affinity Mapping
- July 6th to July 20th: Finalizing colors & typography.
      - July 13th: Half-way check-in asynch (slack) or quick zoom call for any questions, comments, feedback. Please update me of your progress.
      - July 20th @ 2pm: Finalize colors & typography.
- July 20th to Aug 3rd: Finalize logo & Complete brand book.
      - Assign someone to finalize logo. Assign someone to complete brand book.
      - July 27th: Half-way check-in asynch or quick zoom call for any questions, comments, feedback
      - Aug 3rd @ 2pm: Finalized logo with brand colors & completed brand book.
- Aug 3rd to Aug 24th: Create other design components.
      - Priority: Google slides > email signature > form header/color for form > document template > spreadsheet template
- Aug 24th to Sept 7th: Complete Design Process Overview on UIUX Wiki. Complete documentation on road maps.
- Sept 7th: Done!

- Slides: Compile Data Analysis & Logo Findings. Present at future CoP meeting and thank Community for input.
      - Discuss timing of presentation.

### Tasks

- @vivian9w 
      - 
- @yychoco91
      - 

### Items for next agenda

-

**Comment by nguyen-jenn** [comment]
## [07/20/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting



### FYIs (nothing needs to be done, just keeping each other informed)

- Brand Book: [example from TWE](https://github.com/hackforla/internship/wiki/Internship-Brand-Book). Consists of tagline, mission, personality, attributes, values.
- Design Process Overview: [example from TWE](https://github.com/hackforla/internship/wiki/Design-Process-Overview). For our purposes, prioritize brand book, color palette, typography, logo & lastly google slides. If time allows, create email signature, header for forms, color for forms, document templates, spreadsheet templates 

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [Branding/Design Systems 2023 Google Drive](https://drive.google.com/drive/folders/1Va4ExU39N65-vYZAObrq8vBDXyspDYvc?usp=drive_link)
 - [UIUX CoP Design Systems Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)

### New Items 

- [Branding Roadmap](https://github.com/hackforla/UI-UX/issues/472)
- [Research Roadmap](https://github.com/hackforla/UI-UX/issues/473)

### Notes from meeting

Rough Timeline:
- July 20th to Aug 3rd: Finalize logo & Complete brand book.
      - July 27th: Half-way check-in asynch or quick zoom call. First set of logo iteration including colors complete.
      - Aug 3rd @ 2pm: Finalized logo with brand colors & completed brand book.
- Aug 3rd to Aug 24th: Create other design components.
      - Priority: Google slides > email signature > form header/color for form > document template > spreadsheet template
- Aug 24th to Sept 7th: Complete Design Process Overview on UIUX Wiki. Complete documentation on road maps.
- Sept 7th: Done!

- Slides: Compile Data Analysis & Logo Findings. Present at future CoP meeting and thank Community for input.
      - Discuss timing of presentation.

### Tasks

- @vivian9w 
      - Complete Brandbook
- @yychoco91
      - Finalize color palette and finalize logo

### Items for next agenda

- Look over logo, color palette, and brandbook.
- Work on design components.

**Comment by nguyen-jenn** [comment]
## [08/03/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting



### FYIs (nothing needs to be done, just keeping each other informed)

- Brand Book: [example from TWE](https://github.com/hackforla/internship/wiki/Internship-Brand-Book). Consists of tagline, mission, personality, attributes, values.
- Design Process Overview: [example from TWE](https://github.com/hackforla/internship/wiki/Design-Process-Overview). For our purposes, prioritize brand book, color palette, typography, logo & lastly google slides. If time allows, create email signature, header for forms, color for forms, document templates, spreadsheet templates 

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [Branding/Design Systems 2023 Google Drive](https://drive.google.com/drive/folders/1Va4ExU39N65-vYZAObrq8vBDXyspDYvc?usp=drive_link)
 - [UIUX CoP Design Systems Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)
 - [Branding Roadmap](https://github.com/hackforla/UI-UX/issues/472)
 - [Research Roadmap](https://github.com/hackforla/UI-UX/issues/473)

### New Items 



### Notes from meeting

Rough Timeline:
- Aug 3rd to Aug 24th: Finalize brand book. Create other design components.
      - Priority: Google slides > email signature > form header/color for form > document template > spreadsheet template
- Aug 24th to Sept 7th: Complete Design Process Overview on UIUX Wiki. Complete documentation on road maps.
- Sept 7th: Done!

- Slides: Compile Data Analysis & Showcase New Branding. Present at future CoP meeting and thank Community for input.
      - Discuss timing of presentation.

### Tasks

- @vivian9w 
      - Finalize Brandbook
- Everyone
      - Research how to make google slides template @nguyen-jenn 
      - Start brainstorming slides on Figma, transfer to google slides once set up @yychoco91 @vivian9w 

### Items for next agenda

- Finalize design components.

**Comment by nguyen-jenn** [comment]
## [08/24/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting



### FYIs (nothing needs to be done, just keeping each other informed)

- Brand Book: [example from TWE](https://github.com/hackforla/internship/wiki/Internship-Brand-Book). Consists of tagline, mission, personality, attributes, values.
- Design Process Overview: [example from TWE](https://github.com/hackforla/internship/wiki/Design-Process-Overview). For our purposes, prioritize brand book, color palette, typography, logo & lastly google slides. If time allows, create email signature, header for forms, color for forms, document templates, spreadsheet templates 

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [Branding/Design Systems 2023 Google Drive](https://drive.google.com/drive/folders/1Va4ExU39N65-vYZAObrq8vBDXyspDYvc?usp=drive_link)
 - [UIUX CoP Design Systems Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)
 - [Branding Roadmap](https://github.com/hackforla/UI-UX/issues/472)
 - [Research Roadmap](https://github.com/hackforla/UI-UX/issues/473)
 - [UXUI CoP Slides Master Template](https://docs.google.com/presentation/d/1PQLuqy9RoPlMAfo785EHz_wrtK6iUCNV-WBp83kjRxI/edit?usp=sharing)

### New Items 


### Notes from meeting

- Work on refining google slides
Rough Timeline:
- Aug 24th to Sept 7th: Complete Design Process Overview on UIUX Wiki. Complete documentation on road maps.
- Sept 7th: Done!

- Slides: Compile Data Analysis & Showcase New Branding. Present at future CoP meeting and thank Community for input.
      - Discuss timing of presentation.

### Tasks


### Items for next agenda

**Comment by nguyen-jenn** [comment]
## [08/31/23] Meeting Agenda

### Who was there

@nguyen-jenn
@yychoco91
@vivian9w 

### Prework to prep for meeting

- Work on slide iterations on Figma

### FYIs (nothing needs to be done, just keeping each other informed)

- Brand Book: [example from TWE](https://github.com/hackforla/internship/wiki/Internship-Brand-Book). Consists of tagline, mission, personality, attributes, values.
- Design Process Overview: [example from TWE](https://github.com/hackforla/internship/wiki/Design-Process-Overview). For our purposes, prioritize brand book, color palette, typography, logo & lastly google slides. If time allows, create email signature, header for forms, color for forms, document templates, spreadsheet templates 

### Recurring items: 

 - [Best Practices of Design System Main issue](https://github.com/hackforla/UI-UX/issues/423)
 - [Branding/Design Systems 2023 Google Drive](https://drive.google.com/drive/folders/1Va4ExU39N65-vYZAObrq8vBDXyspDYvc?usp=drive_link)
 - [UIUX CoP Design Systems Figma](https://www.figma.com/file/hMJqt0wQVxsIpDAuIQhvRG/UI%2FUX-CoP-Main-File?node-id=1%3A3&t=at72gGLWEWDByuPQ-1)
 - [Branding Roadmap](https://github.com/hackforla/UI-UX/issues/472)
 - [Research Roadmap](https://github.com/hackforla/UI-UX/issues/473)
 - [UXUI CoP Slides Master Template](https://docs.google.com/presentation/d/1PQLuqy9RoPlMAfo785EHz_wrtK6iUCNV-WBp83kjRxI/edit?usp=sharing)

### New Items 


### Notes from meeting

- Created component library

Rough Timeline:
- Aug 31st - Sept 7th: Completing Slide variations + variant components. Create template for documents. Work on completing documentation.

- Slides: Compile Data Analysis & Showcase New Branding. Present at future CoP meeting and thank Community for input.
      - Discuss timing of presentation.

### Tasks

- @yychoco91 @vivian9w @nguyen-jenn Completing Slide variations + variant components. Create a template for documents. Work on completing documentation.

### Items for next agenda

- Ensure all pieces have been completed

**Comment by Aparna1Gopal** [comment]
This project is complete and this agenda issue is being closed.
