### ISSUE TITLE
UI/UX CoP Ambassadors for Onboarding - Recruitment Tracker

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#458]
### Overview
Recruit UI/UX CoP Ambassadors for the fortnightly Onboarding. This issue tracks the impact of the recruitment efforts. 

### Action Items
- [x] Send the Slack call for UI/UX Ambassador sign-ups 
- [x] Record Slack call 
- [x] Record the sign-ups & their details in this issue
- [x] Share the resources section in this issue with the sign-ups to bring them upto speed 
- [x] Request their registration for next onboarding using this Meetup schedule
- [x] Update Admin regarding members available/not available for Onboarding the week prior 
- [ ] ~~Training of Ambassadors: Common questions received during Onboarding~~  No sign-ups/or sign-ups were not available on the day of onboarding
   - [ ] ~~UI/UX related: What are the open roles? How do we find them? What do we do next?~~
   - [ ] ~~Code of Conduct~~
   - [ ] ~~Cross-verify the GitHub & Slack (Tables Project)~~

### Resources/Instructions
[Common FAQs for onboarding and new UI/UX members](https://github.com/hackforla/UI-UX/issues/319)
[Self-Onboarding Slide Deck](https://docs.google.com/presentation/d/1DGEuS_GDMBSJAfu_yq18vtSvkMjiYksPAdWp6SPsG1M/edit#slide=id.p)
[Code of Conduct](https://www.meetup.com/en-AU/hackforla/)
[Schedule of Onboarding – Meet-up](https://github.com/hackforla/codeofconduct)
Tables Project/Database

**Comment by Aparna1Gopal** [comment]
Slack Announcement on April 06,2023

:wave: Hi All! We are looking for UI/UX AMBASSADORS to support us at the next Onboarding!
:spiral_calendar_pad: When: April 10,2023 - 6PM PST
:round_pushpin: Where: [Meetup](https://www.meetup.com/en-AU/hackforla/events/vfknzsyfcgbfb/)
:rocket: What’s in it for you?
A splendid opportunity to represent the UI/UX Community of Practice as our Ambassador!
Not to mention, hone your other UX soft-skills like: communication, talking to diverse user groups, troubleshooting & problem solving on the fly, being a peer mentor, be nimble on your feet to pivot as/when required, and a lot more..
:pencil2: Sign-up & confirm your participation in this thread:thread:
Thank You!
UI/UX CoP co-leads
[at Julia Gab]
[at Jennifer Nguyen]
[at Aparna Gopal]

<img width="991" alt="Screenshot 2023-04-19 at 12 53 22 pm" src="https://user-images.githubusercontent.com/86335455/232999705-b3afc079-c0eb-4dfd-9f88-57eccbbc4fd3.png">

**Comment by Aparna1Gopal** [comment]
### Slack Admin Message 

Hi Admin and [at Bonnie]
 FYI: For the next Onboarding on April 10, the following members from the UI/UX CoP are available to provide Onboarding support.
Jennifer N [Co-Lead]
Aparna G [Co-Lead]

<img width="1018" alt="Screenshot 2023-04-19 at 12 55 28 pm" src="https://user-images.githubusercontent.com/86335455/233000425-820ca93d-dfd6-4e36-87ad-47a83e7568fa.png">

**Comment by Aparna1Gopal** [comment]
### Slack Call-out on May 03, 2023 for next Onboarding

<img width="1051" alt="Screenshot 2023-05-04 at 10 05 14 am" src="https://user-images.githubusercontent.com/86335455/236113304-bda8f6e6-7633-4f58-b8d2-47c44b056609.png">

**Comment by Aparna1Gopal** [comment]
### Slack Message (on May 08, 2023) - Post Onboarding 

:wave: Hi All! Nice meeting you at the Onboarding tonight!
:books:You can find past activities of the UI/UX Community of Practice in our [Wiki here](https://github.com/hackforla/UI-UX/wiki)
:hourglass_flowing_sand: See you at the next UI/UX Community of Practice meeting on Wednesday, 6PM PT

<img width="823" alt="Screenshot 2023-05-09 at 9 56 02 am" src="https://user-images.githubusercontent.com/86335455/236993794-c3e683c2-b982-48f3-84a3-710ef006b3ad.png">

**Comment by Aparna1Gopal** [comment]
**Notes**

- This recruitment method was carries out from April to June 2023, bi-weekly to recruit for Onboarding support/help
- Either there were no sign-ups or the ambassadors that did sign-up were not available on the day of Onboarding 
- This recruitment method was not very successful in obtaining additional Onboarding support & is thus being closed. Alternate means of obtaining additional Onboarding support will be explored.
