### ISSUE TITLE
Workshop: UX Mock Whiteboard Challenge Prep

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#465]
### Overview

- This is a workshop conducted during the weekly UI/UX Community of Practice meeting.
- Goal of the workshop is to provide practice & feedback on UX Whiteboard Challenges for Job Interviews. By the peer mentors in the community.

### Action Items

- [x] Identify all available resources pertaining to this issue within the UI/UX CoP Google Drive
- [x] Collate all relevant resources in this Issue, under Resources/Instructions
- [x] Share the [Guide](https://www.coursera.org/articles/preparing-for-the-whiteboard-design-challenge) with the community, prior to the Workshop, for quick prep/overview
- [x] Share this [Issue](https://github.com/hackforla/UI-UX/issues/465) with the community during the Workshop
- [x] Share link to the [FigJam workspace](https://www.figma.com/file/boYOVROdfo5AEmb68R9D7G/UIUX-CoP-FigJam?type=whiteboard&node-id=0-1&t=5xsvF5DJksGlhM3r-0), with the community during the Workshop
- [x] Share [Instructions](https://github.com/hackforla/UI-UX/issues/465#issuecomment-1549050550) for the UX Whiteboard Challenge
- [x] Share the [Prompts](https://github.com/hackforla/UI-UX/issues/465#issuecomment-1549100187) for the UX Whiteboard Challenge
- [x] Conduct round table mock-interviews, provide peer feedback
- [x] Note any additional resources shared during the workshop, in this issue. Encourage community members to do the same
- [x] Update resources in the Google Drive, if required
- [x] Update [Wiki](https://github.com/hackforla/UI-UX/wiki/Workshop-Series)
- [x] Share screenshot of collaborative FigJam workspace in comments, if applicable
- [x] Update Slack Message call-outs in comments, if applicable
- [x] Review with Co-Leads & close issue

### Resources/Instructions
[19 whiteboard and take-home design challenges for UX designers, UX Design Institute](https://www.uxdesigninstitute.com/blog/design-challenges-for-ux-designers/)
[How to Prepare for the Whiteboard Design Challenge: A Guide, Coursera](https://www.coursera.org/articles/preparing-for-the-whiteboard-design-challenge)
[UX Whiteboard Challenge, SOLVE WHITEBOARD CHALLENGES](https://www.uxwbchallenge.com/#Instructions)
[UX Whiteboarding Challenge Info, Resources & Links from CoP meetings](https://docs.google.com/document/d/1S7MaBRqm8N6tMC96yyI9yjKJvjMokW2KvRABAHWko5I/edit)

**Comment by Aparna1Gopal** [comment]
### Instructions for the UX Whiteboard Challenge
 - Give Introduction for UX Whiteboard Challenge (What is it? Why do companies conduct it?) 
 - Provide the resource/notes on how to answer/respond to UX Whiteboard Challenges 
 - Provide 2 prompts for the UX Whiteboard Challenge. Members can choose to work on **_one_** of the prompts. Based on the domain they specialise in - example: UX Research, Design, Writing, Generalist etc. 
 - Allocate 20-minutes for members to complete their Whiteboard Challenge on the FigJam. The short time-frame is to emulate the time-sensitive real-world conditions of job interviews. 
 - Co-Leads will function as moderators/hiring managers. Members can choose to ask follow-up questions during the course of these 20-minutes as they work on their concepts during the Whiteboard Challenges. To emulate Job Interviews. 
 - Members can choose to write, draw, sketch, add pictures etc. on their FigJam to explain their concepts & solution derivation. 
 - Allocate 5-10 minutes to each member to present their solutions to the Whiteboard Challenge & for peer feedback from other community members.

**Comment by Aparna1Gopal** [comment]
### UX whiteboard challenge examples/prompts

1. Speed Costco checkout

“We want to improve the Costco customer experience by eliminating the long lines at checkout. We’ve decided a self-checkout process is our solution but we want to do better than the typical self-checkout at grocery stores. Our research has shown they’re even slower than the usual checkout lanes.”

Find the entire prompt on [100 Days of Design](https://100days.design/index.php/whiteboard-challenges/)

 

2. Bank chatbot

“You are a design director for a large national bank. Your bank wants to be ready to launch an app that will allow your customers to access their account information via a chatbot. How do you approach the challenge of providing information via a series of requests?”

Find the entire prompt on [100 Days of Design](https://100days.design/index.php/whiteboard-challenges/)

3. Jeans

“Shopping for jeans and other form-fitting apparel online could be time-consuming and frustrating. It’s hard to compare different styles and it’s hard to know for sure how they will fit. It’s a disappointing experience when you have to return an item that doesn’t fit quite right. How can you help customers select the style of jeans that they’re looking for in the right size?”

Find the entire prompt on [UX Challenge](https://www.uxchallenge.co/)

 

4. Elevator lobby

“Our elevators work great, however, with over 2500 people using our elevators every day, we need a better system to get everyone to the right one.”

Find the entire prompt on [100 Days of Design](https://100days.design/index.php/whiteboard-challenges/)

 

5. Subscription fees

“It’s hard to keep track of all the products and services that we have subscribed to every month. All we see is money deducting from our accounts, sometimes from services that we don’t need anymore. How can you design a product which helps manage subscriptions?”

Find the entire prompt on [UX Challenge](https://www.uxchallenge.co/)

 

6. Time machine

“We’ve invented an app that is easy to download onto your smartphone or smartwatch. It allows you to travel to any time in the past or future. But we’re having trouble designing the interface.”

Find the entire prompt on [100 Days of Design](https://100days.design/index.php/whiteboard-challenges/)

 

7. Pet watch

“No matter how much we love our pets, we still need to leave home to go to work, travel, run errands… leaving our pets home alone and sad. How can you enable pet owners to interact with their pets when they’re not at home?”

Find the entire prompt on [UX Challenge](https://www.uxchallenge.co/)

 

8. App for kids

“We run a bespoke toy company and want to build an app for kids to design their own toys (which we will build).”

Find the entire prompt on [100 Days of Design](https://100days.design/index.php/whiteboard-challenges/)

 

9. Invoices

“Managing multiple clients and projects is a part of running a business as a freelancer. However, sometimes clients don’t pay on time. How do you help freelance business owners keep track of payments from their clients and make sure that they receive payments from clients promptly for every project?”

Find the entire prompt on [UX Challenge](https://www.uxchallenge.co/)

 

10. Car locator

“We have over 15,000 employees and all of their cars on our main campus. Employees have been ‘losing’ their cars in the lot. They forget which of the 5 giant parking lots they parked in and are wandering around clicking their door alarms to find their cars. The noise pollution at the end of the day is terrible. We already have a company app. We want to add a feature to help employees find their cars.”

Find the entire prompt on [100 Days of Design](https://100days.design/index.php/whiteboard-challenges/)

**Comment by Aparna1Gopal** [comment]
### 3 PROMPTS for UX WhiteBoard Challenge 

- **Speed Costco Checkout**
**Improve the Costco customer experience by getting rid of long lines at checkout.**

We want to improve the Costco customer experience by getting rid of the long lines at checkout. We’ve decided a self-checkout process is our solution, but we want to do better than the typical self checkout at grocery stores. Our research has shown they’re even slower than the usual checkout lanes. 

Constraints
We’re only interested in existing technology that we can implement immediately. 
We want to be sure people are paying for every item they take out of the store. 
Everyone must be able to buy their goods, but not everyone should have to use your solution.

**Comment by Aparna1Gopal** [comment]
### Collaborative FigJam workspace

<img width="820" alt="Screenshot 2023-05-18 at 8 11 22 am" src="https://github.com/hackforla/UI-UX/assets/86335455/ad4bca11-42a2-4d5a-8b4a-8b7b2c4e4d45">

<img width="435" alt="Screenshot 2023-05-18 at 8 11 41 am" src="https://github.com/hackforla/UI-UX/assets/86335455/acc31c4d-0d67-42d1-aea4-2b086a44524b">

<img width="832" alt="Screenshot 2023-05-18 at 8 12 01 am" src="https://github.com/hackforla/UI-UX/assets/86335455/da47245d-99a0-4d97-a066-a149056fb62b">

**Comment by Aparna1Gopal** [comment]
### Slack Call-outs/Announcements

<img width="1050" alt="Screenshot 2023-05-18 at 8 15 06 am" src="https://github.com/hackforla/UI-UX/assets/86335455/60a15c77-f949-402b-bd69-a9d51cf28a0a">

**Comment by Aparna1Gopal** [comment]
### Slack Call-outs/Announcements

<img width="1024" alt="Screenshot 2023-05-18 at 10 02 16 am" src="https://github.com/hackforla/UI-UX/assets/86335455/9c68e95e-67f5-40cd-989d-2e217a2dd07d">

Hi All! Thank You for your active & enthusiastic participation in today’s UX Whiteboard Challenges! There was so much to learn all around! And the support from the community was truly phenomenal!:pray::bulb::closed_book::charmander_dancing:
The resources from today’s workshop can be found [here](https://github.com/hackforla/UI-UX/issues/465)
Other resources can be found in the [UI/UX Wiki](https://github.com/hackforla/UI-UX/wiki)

**Comment by Aparna1Gopal** [comment]
This Workshop is complete & the issue is being closed.
