### ISSUE TITLE
Onboarding Project: Create Research Roadmap

### ISSUE THREAD

**Issue by kevinmoutoucarpin** [hackforla/UI-UX#469]
### Overview
We need to create the Roadmap Google Doc for Hack for LA Onboarding Research so that we can keep track of basic details across all research plans.

### Action Items

- [ ] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [ ] Create a new page on the wiki for the roadmap called: `Research Overview` using the template for Research Roadmap 
  - [ ] link it to the Research Output Overview wiki page
- [ ] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [ ] Put back in Prioritized Backlog under new milestone
- [ ] Go to the Google Drive, UI/UX (Community of Practice), Research: UI/UX CoP, Onboarding Project, Folder
  - [ ] Create a new folder in the Google Drive called [02. Research Roadmap]
- [ ] Make a new document using the report template
  - [ ] Move your document from "My Drive" to the shared drive Onboarding Project folder that you just created
- [ ] Name your document to be called Onboarding Project: Research Roadmap
- [ ] Brainstorm with the team what research the team should do for Hack for LA Onboarding and provide basic details for each research plan 
   - Goals
   - Requirements
   - Timelines
   - Delivery
   - Follow-up Options
   - Research Analysis
- [ ] Update the Table of contents (page 2) when you are finished with document
- [ ] Research lead reviews roadmap
- [ ] Product reviews roadmap

### Resources
- [Onboarding Project: Research Roadmap](https://docs.google.com/document/d/1LIRYyG0KL0Qyw0G5eExWuXd9XuYSVjfE-oj0chKsxSk/edit#)
