### ISSUE TITLE
Roadmap: UI/UX CoP Guest Speakers YouTube Channel/Playlist

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#475]
### Overview
All required tasks to set-up the YouTube playlist of past guest speakers from the UI/UX CoP repository is documented

### Action Items
- [ ] Create Epic Issue to document all Consent Forms
- [ ] Create Epic Issue to document all YouTube Uploads 
- [ ]  Send & record emails to Speakers (seeking consent) - use HfLA gmail ID, with CC to Co-Leads 
- [ ] Access to HfLA’s YouTube Channel - required OnePassword vault
- [ ] Identify details/template for each video upload
  - [ ]  Name of Speaker
  - [ ] Date (Month, Year), 
  - [ ] Topic
  - [ ] Speaker Introduction/ Blurb
  - [ ] Keywords/Tags (3-5 keywords for each speaker)  

### Resources/Instructions
- [Hack for LA YouTube Channel](https://www.youtube.com/@hackforla/featured)
- [UI/UX CoP Wiki of past Guest Speakers](https://github.com/hackforla/UI-UX/wiki/past-speakers)

**Comment by Aparna1Gopal** [comment]
### Notes - Slack Communication

![Image](https://github.com/user-attachments/assets/135a5dcb-3007-4b48-a4a1-719580cbacb4)

![Image](https://github.com/user-attachments/assets/efd4db61-6105-480d-b5d9-7c619c7e0acc)

![Image](https://github.com/user-attachments/assets/7abcb739-4b08-44f9-98f2-6fa7505ef9cb)

**Comment by Aparna1Gopal** [comment]
### Notes - Slack Communication - Admin

<img width="1447" alt="Screenshot 2024-11-28 at 10 10 57 am" src="https://github.com/user-attachments/assets/fb24911d-289b-43b8-a9ad-557197b63fca">

**Comment by Aparna1Gopal** [comment]
### Epic Issue to Document all steps required for Guest Speaker
**Notes of steps required in this Epic Issue**
**Epic of all epics for Guest Speaker** 

- This Epic should capture all end-to-end steps required from the sourcing to hosting to Youtube upload of Guest Speaker 
- Reach out to Guest Speaker using LinkedIn, Slack, Email, Personal Networks etc. Introduce and provide examples of Past Guest Speakers 
- Once Guest Speaker is confirmed, move conversation to ui-ux gmail address. Use (add gmail address) or CC for all communication moving forward. Instructions for Speaker Series shared. Templates of emails available in the official gmail archives of past speakers 
- Prepare Meetup Invite for Guest Speaker. Liase with Admin to draft and post Meetup announcement. Liase with admin to provide access to Webinar (Zoom 4) account 
- Generate Community Questions for Guest Speaker 
- Collect Consent Form from Guest Speaker 

- POST COMPLETION OF TALK - 
- Send Thank you email to guest speaker
- Upload talk Recording on google drive
- Upload talk on UI/UX YouTube channel 
- Update Talk on the UI/UX [Wiki](https://github.com/hackforla/UI-UX/wiki/Past-Speakers)
- Shared the Recording of the talk (either from Google Drive or YouTube) with the UI/UX CoP on Slack for wider reach
- Review all issues - complete and close

**Comment by Aparna1Gopal** [comment]
### GUEST SPEAKER PLAYBOOK - IDEAS

- An Epic to document any slack communication within Co-Leads, Admin etc. for Guest Speakers starting in 2026 (new system). This will be the main epic issue for all new speakers. [Previously, this step was consolidated within one issue - [the Guest Speaker Question issue](https://github.com/hackforla/UI-UX/issues/355). This Guest Speaker Question issue is public and is posted widely and advertised widely (on Meetup, Slack channels etc.). Posting internal slack communication (by the UI/UX Co-leads, Admin etc.) on this public Guest Speaker Question issue may not be a viable long-term option]. 
- Under this Guest Speaker epic issue should be other sub-epics (that address Guest Speaker Questions, Consent, Uploading talk video - on HfLA Google drives and Youtube upload). 
- The Guest Speaker epic issue is used primarily in the PLAYBOOK Wiki. It should address details on reaching out to Guest Speakers (networking/outreach aspect of the process. Communication throughout the process via email (with CC: uiux@hackforla.org), sending consent forms, thank you email at the end of the talk. 
- This Playbook can be tested with the community and cop-leads channel once complete, to identify the efficient of this Playbook and iterate from there (if required).
