### ISSUE TITLE
Tracker: Roll-Call of UI/UX CoP Co-Leads available for bi-weekly Onboarding 

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#476]
### Overview
This issue keep track of the roll-call & availability of the UI/UX CoP Leads for Onboarding 

### Action Items
- [ ] Take roll-call during weekly Co-Leads meeting (on Wednesdays, 7PM onwards) or async using Slack 
- [ ] Update Admin via Slack regarding members available/not available the week prior to Onboarding 
- [ ] Record Slack call
- [ ] Repeat Process for next Onboarding 

### Resources/Instructions
- [Common FAQs for onboarding and new UI/UX members](https://github.com/hackforla/UI-UX/issues/319)
- [Self-Onboarding Slide Deck](https://docs.google.com/presentation/d/1DGEuS_GDMBSJAfu_yq18vtSvkMjiYksPAdWp6SPsG1M/edit#slide=id.p)
- [Code of Conduct](https://www.meetup.com/en-AU/hackforla/)
- [Schedule of Onboarding – Meet-up](https://github.com/hackforla/codeofconduct)
- Tables Project/Database

**Comment by Aparna1Gopal** [comment]
### Slack Announcement 
<img width="1059" alt="Screenshot 2023-07-13 at 2 15 53 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/db372162-44f3-4f10-bb4f-aeb90490d590">

**Comment by Aparna1Gopal** [comment]
### Slack Announcement

Hi Admin and 
[@Bonnie](https://hackforla.slack.com/team/UE1UG1YFP)

FYI: For the next Onboarding on July 17, the following members from the UI/UX CoP are available to provide Onboarding support.
Jennifer N [Co-Lead]
Aparna G [Co-Lead - From 7:30PM onwards]
Julia G [Co-Lead - 8-9PM]
Could you also please provide us with the Panelist Zoom link? As we were unable to join the last onboarding on July 10. Thank You!
https://hackforla.slack.com/archives/C01Q24YF56J/p1689037783727019?thread_ts=1689036730.949279&cid=C01Q24YF56J

<img width="1058" alt="Screenshot 2023-07-13 at 2 16 04 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/223f9f1e-f6bb-4d53-be51-fc5ae281f50f">

**Comment by Aparna1Gopal** [comment]
### Slack Admin Update 

<img width="1042" alt="Screenshot 2023-07-21 at 2 03 36 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/05142236-43ea-4ac5-8ff1-89dbf747c3d2">

**Comment by Aparna1Gopal** [comment]
### Slack Admin Update

<img width="1055" alt="Screenshot 2023-08-14 at 2 36 45 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/789da8cc-db0e-471b-9242-172fb88fb531">

**Comment by Aparna1Gopal** [comment]
### Slack Admin Update
<img width="1013" alt="Screenshot 2023-08-26 at 2 17 32 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/ebacf2f2-f3b2-4e2c-90f5-fd3e77523326">

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in September

- September 11, 2023: Attended by Jennifer N 
- September 26, 2023: Attended by Peter G & Aparna G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in October

- October 16, 2023: Attended by Peter G
- October 24, 2023:

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in November 

November 07, 2023: Attended by Peter G & Aparna G

**Comment by Aparna1Gopal** [comment]
### No Onboarding in December - Break

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in January 2024 

- January 02,2024: No Co-Leads available 
- January 16, 2024: Jennifer N, Peter G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in February 2024 
- February 05, 2024: Aparna G
- February 20, 2024: Peter G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in March 2024 
- March 04,2024 : Aparna G, Peter G
- March 26,2024 : Julia G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in April 2024 
- April 09,2024 : Aparna G, Peter G
- April 24,2024 : Peter G, Julia G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in May 2024 
- May 06,2024 : Aparna G, Peter G
- May 21,2024 : Julia G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in June 2024 
- June 03,2024: Aparna G, Peter G
- June 18,2024: Aparna G, Peter G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in August 2024

- August 05, 2024: Aparna G, Peter G
- August 20, 2024: Peter G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in September 2024
- Sept 09 (Monday) - Peter G
- Sept 24 (Tuesday) - Julia G, Aparna G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in October 2024

October 07, 2024: Aparna G
October 22, 2024: Peter G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability in November 2024

November 04, 2024: Aparna G, Peter G
November 19, 2024: Aparna G, Peter G

**Comment by Aparna1Gopal** [comment]
### Onboarding Co-Lead Availability January 2025

January 06, 2025 (Part 1): Aparna G
January 13, 2025 (Part 2): Peter G
January 20, 2025 (Part 1 & 2): Aparna G

**Comment by pogwon** [comment]
### February 4, 2025 Onboarding Notes

- Helped two members onboard
- Both hoped to prioritize networking, career development, and skills development (technical and soft skills).

**Comment by Aparna1Gopal** [comment]
### February 19, 2025 Onboarding Notes
- Helped 6 people onboard
- Asked the following 3 questions during introductions: Who they are? What brings them to HfLA? What are they hoping to get out of their time at HfLA? 
- The common themes included: Get real-world practical experience, currently in-between jobs and wanting to get experience for their portfolios, currently generalist wanting to transition to a specialist role, understand the workings & requirements of the tech industry and the current tech scenario. 
- One member joined HfLA on the recommendation from a friend as an org to get real-world experience (word-of mouth reputation of HfLA as a space to gain real-world experience documented)

**Comment by Aparna1Gopal** [comment]
### March Onboarding Notes

Co-Leads Availability 

March 01 - Peter G & Aparna G 
March 18 - Peter G 
March 31 - Aparna G

**Comment by Aparna1Gopal** [comment]
### March 03, 2025 Onboarding Notes

- Peter G and Aparna G helped six members onboard
- Common themes: Get real-world practical experience, get experience for their portfolios, deciding between their specialities in design and/or research. 
- With the updated system for researchers, triaged the designers, content writers and researcher accordingly.

**Comment by pogwon** [comment]
### March 18, 2025 Onboarding Notes

- Helped one new member onboard
- Mostly wanted to focus on developing technical skills and career development. Making a career switch into UX Design.

**Comment by Aparna1Gopal** [comment]
### March 31, 2025 Onboarding Notes
- Helped one member onboard. 
- Member was looking to gain practical experience working on real-world projects at HfLA. Was recommended to join the org by a friend (word-of mouth reputation of HfLA as a space to gain real-world experience documented)

**Comment by Aparna1Gopal** [comment]
### April 16, 2025 
- Met with new members post-onboarding via Slack and the UI/UX CoP Wednesday 6PM PT Meeting
- Helped one member with registering for Zoom meetings (via Slack)
- Helped two members during the UI/UX CoP Wednesday 6PM PT. Assisted with the onboarding process, joining ui-ux slack channels, testing/feedback on the updated experience profile, open roles project board. 
- Both members were focussed on UX Design and transitioning from Graphic Design. They wanted to get experience working on real-world projects and gain more collaborative experience. Also spoke about using experience gained at HfLA for their portfolios.

**Comment by Aparna1Gopal** [comment]
### April 28, 2025 Onboarding Notes

- Helped one member onboard.
- Member was looking to gain practical experience working on real-world projects at HfLA after having graduated with an HCI/HCD degree. Was recommended to join the org by a mentor on ADP-List (word-of mouth reputation of HfLA as a space to gain real-world experience documented). Member was also interested in the community aspect of HfLA. Was interested in UXR and PM and exploring all over-lapping avenues as they decide on their career path.

**Comment by Aparna1Gopal** [comment]
### May 13, 2025 Onboarding Notes 

- Helped one member onboard.
- Member was looking to get experience in UX design as they already had some experience working in web design. Had heard of HfLA from their network and onboarded to gain practical experience.

**Comment by pogwon** [comment]
### June 16, 2025 Onboarding Notes

- Helped 9 members onboard (7 designers, 2 researchers)
- Most were looking for networking opportunities, portfolio projects, and experience working cross-functionally. The overall theme was overwhelmingly career development.

**Comment by Aparna1Gopal** [comment]
### August 12, 2025 Onboarding Notes 

- Peter G and Aparna G helped six members onboard (2 UXRs, 2 UXDs, 1 UX Writer, 1 PM/Design) 
- Members were looking for experience in the UX space, portfolio building, pivoting into a new career in UX and gain further experience & networking. 

<img width="942" height="332" alt="Image" src="https://github.com/user-attachments/assets/de2d40ba-1ab9-4809-a0ed-cda2df16ddf5" />

**Comment by Aparna1Gopal** [comment]
### August 25, 2025 Onboarding Notes

- Peter G and Aparna G helped five members onboard (all UX Designers)
- Members were looking for experience in the UX space, portfolio building, gain further practical experience. 
- As per requirement of TDM- Calc and TWE (Projects very actively looking for designers), these projects were spoken of at length at the UI/UX onboarding. Other open roles were also shared. 
- UI/UX Community of Practice activities were shared. TDM-Calc Usability testing recruitment message was also shared (a good low-stakes way for members to know (1) How a usability testing is conducted (2) A good way to contribute to a project while they are newly onboarded and still deciding on a full-fledged project


<img width="991" height="348" alt="Image" src="https://github.com/user-attachments/assets/71ccb370-8c74-498a-bc63-6e880f140007" />

**Comment by Aparna1Gopal** [comment]
### September 09, 2025 Onboarding Notes
- Aparna G helped 4 members onboard 
- 2 UX Researchers, 1 UX Designer (returning member), 1 PM/UX/Software Engineering member
- Shared UI/UX Slack channel, UI/UX Wiki, Open Roles during Onboarding. Shared bookmarking tip for easy/repeat access. 
- Goals included pivoting successfully into the UX space from a different career - hence need to develop more UX specific skills at HfLA (from their previous career/background in software engineering, academia, anthropology)

**Comment by pogwon** [comment]
### September 22, 2025 Onboarding Notes
- Peter G helped 3 members onboard 
- All Designers/Researchers (leaning towards design) and one returning member
- Shared UI/UX Slack channel, UI/UX Wiki, Open Roles, with emphasis on TWE and TDM-Calculator urgently needing members. Shared bookmarking tip for easy/repeat access. 
- Two were people transitioning from other areas in tech (dev. and tech analysis) and one is still a student. All were looking to network, gain real world experience, and portfolio projects.

**Comment by Aparna1Gopal** [comment]
### October 07, 2025 Onboarding Notes
- Peter G and Aparna G helped one member onboard. 
- Shared UI/UX Slack channel, UI/UX Wiki, Open Roles during Onboarding with emphasis on TDM-Calculator urgently needing UX Designers. 
- Goals included gaining real-world experience in the UX space while pivoting from a different creative career.

**Comment by Aparna1Gopal** [comment]
### October 20, 2025 Onboarding Notes
- No UI/UX members onboarding. 

<img width="1424" height="101" alt="Image" src="https://github.com/user-attachments/assets/76b3d73c-7403-4e3a-8fa5-9416b1abcfec" />

**Comment by Aparna1Gopal** [comment]
### November 04, 2025 Onboarding Notes
- Aparna G helped 4 members onboard 
- 3 UX Researchers & 1 UX Designer 
- 2 members recommended by Dr.Sandra Oh from Cal Poly Pomona to intern at HfLA. Dr.Oh was has been with HfLA previously (TWE Project) and also been a Guest Speaker at the UI/UX CoP. 
- Shared UI/UX Slack channel, UI/UX Wiki, Open Roles during Onboarding with emphasis on TDM-Calculator & TWE urgently needing UX Designers (as specified by Bonnie during onboarding - with specific UXD requirements for TDM-Calc & TWE teams/projects). 
- Most members were pivoting from other disciplines to UX - Anthropology & Linguistics & Community work (EMT) to UXR, Graphic Design to UXD. 
- Goals included gaining real-world experience in the UX space while pivoting from a different career, internships in Anthropology as required for their coursework, new graduates (undergrad & PhDs) looking for industry experience. 

<img width="1005" height="321" alt="Image" src="https://github.com/user-attachments/assets/42c6ffa9-a1cb-4c75-bc91-4fb8a4ba9783" />

**Comment by Aparna1Gopal** [comment]
### January 05, 2026 Onboarding 

- Co-Leads (Peter G and Aparna G) attended onboarding. 
- 2 UXRs and 1 UXD onboarded. 
- Shared all onboarding UX resources.

**Comment by Aparna1Gopal** [comment]
### February 24, 2026 Onboarding
- Co-Lead Aparna G attended onboarding 
- 1 UXR Onboarded. They had experience in theatre arts, anthropology and were working with the LADOT. Wanted to expand their experience in UX Research and civic tech. Introduced them to TDM-Calc project since at last all-leads meeting, requirement of UXRs for TDM-Calc project was discussed. 
- Shared all other onboarding resources.

**Comment by Aparna1Gopal** [comment]
### March 23, 2026 Onboarding 
- Co-Lead Aparna G attended onboarding
- 5 new UX members onboarded. Onboarded them both async and in real-time. 
- Shared all onboarding resources. Triaged them based on their experience and interests and long-term career goals. 
- Used onboarding spreadsheet to review new onboarding members. 
- Shared all other onboarding resources.
- Template of slack message sent post-onboarding
- TEMPLATE
:wave: Hi All! Thanks for attending the Onboarding today and WELCOME! :party_blob:
:slack: Post any questions you have, in this [UI/UX Slack channel](https://hackforla.slack.com/archives/C017ESHSMNG)
:books: Find past activities of the UI/UX Community of Practice in our [Wiki here](https://github.com/hackforla/UI-UX/wiki)
:hourglass_flowing_sand: See you at the next UI/UX Community of Practice meeting on Wednesday, 6PM PT - [Upcoming Meetings](https://github.com/hackforla/UI-UX/wiki#upcoming-meetings-) - [Zoom Info](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09)
Find UI/UX Open roles
:art: [Design](https://github.com/orgs/hackforla/projects/67/views/4)
:memo: [Writing/Content Design](https://github.com/orgs/hackforla/projects/67/views/9)
:ledger:[Research - follow steps given in this Slide Deck (Slide 37)](https://docs.google.com/presentation/d/1ih07A0oXvG80J5Tf_Ak0ncixkdO3xRSvlk6f7zAuk7w/edit#slide=id.g3325c4cb49e_0_51)
- SCREENSHOT 

<img width="984" height="305" alt="Image" src="https://github.com/user-attachments/assets/9b3188e0-1f24-4898-bb39-7c507663f5ce" />

**Comment by Aparna1Gopal** [comment]
### April 21, 2026 Onboarding
- No Co-Leads available for Onboarding. 
- The UI/UX Community of Practice meeting on Wednesday (6PM PT) being used for post-onboarding support.

**Comment by Aparna1Gopal** [comment]
### May 18, 2026 Onboarding
- Co-Lead Aparna G attended onboarding. 
- Onboarded two new members. Both UX Designers. They had experience in Design, Dev, Product Design, Psychology. 
- Shared all onboarding UX resources including UI/UX CoP Wiki and Open Roles. 
- Goals included sharpening their skills in UX Design, working on portfolio projects, gaining leadership skills, networking. 

<img width="975" height="297" alt="Image" src="https://github.com/user-attachments/assets/3d5bb4c8-adc7-42bc-ae6c-eb3e420c28b4" />

**Comment by Aparna1Gopal** [comment]
### August 04, 2026 Onboarding 
- Co-Lead Aparna G attended onboarding.
- Onboarded five new members. All UX Designers. They had varying experience levels in design. Most members had been in design and wanted to hone their design skills further. 
- Shared all onboarding UX resources including UI/UX CoP Wiki and Open Roles.
- Members' Goals included: sharpening skills in UX Design, improving their portfolio and case studies, adding new projects in their portfolio, working on their soft skills. One member was a returning member of HfLA and they were returning after a break. They had previously contributed towards Expunge Assist. They had really liked the atmosphere at HfLA and were re-joining and re-onboarding after their break.

**Comment by Aparna1Gopal** [comment]
### September 14, 2026 Onboarding

- Co-Lead Aparna G attended onboarding.
- Onboarded two new members. 1 UX Designer and 1 UX Researcher. 
- Shared all onboarding UX resources including UI/UX CoP Wiki and Open Roles. And 1-1 meeting setup with Bonnie for UX Researchers. 
- Members' Goals included: Improving their UX Design skills, working in teams, pivoting from academia and getting industry experience. Developing their portfolio and projects on their portfolio. 

<img width="979" height="331" alt="Image" src="https://github.com/user-attachments/assets/cccfe622-f087-4616-baf2-3b1e0a8ff8d2" />
