### ISSUE TITLE
Workshop: UX Mock Whiteboard Challenge Prep

### ISSUE THREAD

**Issue by pogwon** [hackforla/UI-UX#517]
### Overview

- This is a workshop conducted during the weekly UI/UX Community of Practice meeting.
- Goal of the workshop is to provide practice & feedback on UX Whiteboard Challenges for Job Interviews. By the peer mentors in the community.

### Action Items

- [x] Identify all available resources pertaining to this issue within the UI/UX CoP Google Drive
- [x] Collate all relevant resources in this Issue, under Resources/Instructions
- [x] Share the [Guide](https://www.coursera.org/articles/preparing-for-the-whiteboard-design-challenge) with the community, prior to the Workshop, for quick prep/overview
- [x] Share this [Issue](https://github.com/hackforla/UI-UX/issues/517) with the community during the Workshop
- [x] Share link to the [FigJam workspace](https://www.figma.com/file/boYOVROdfo5AEmb68R9D7G/UIUX-CoP-FigJam?type=whiteboard&node-id=0%3A1&t=QcO6ZPw9EZJyzGOE-1), with the community during the Workshop
- [x] Share [Instructions](https://github.com/hackforla/UI-UX/issues/517#issuecomment-1712217540) for the UX Whiteboard Challenge
- [x] Share the [Prompts](https://github.com/hackforla/UI-UX/issues/465#issuecomment-1549100187) for the UX Whiteboard Challenge
- [x] Conduct round table mock-interviews, provide peer feedback
- [x] Note any additional resources shared during the workshop, in this issue. Encourage community members to do the same
- [x] Update resources in the Google Drive, if required
- [x] Update [Wiki](https://github.com/hackforla/UI-UX/wiki/Workshop-Series)
- [x] Share screenshot of collaborative FigJam workspace in comments, if applicable
- [x] Update Slack Message call-outs in comments, if applicable
- [x] Review with Co-Leads & close issue

### Resources/Instructions

[UX Whiteboarding Challenge Info, Resources & Links from CoP meetings](https://docs.google.com/document/d/1S7MaBRqm8N6tMC96yyI9yjKJvjMokW2KvRABAHWko5I/edit)
[How to Prepare for the White Board Design Challenge: A Guide](https://www.coursera.org/articles/preparing-for-the-whiteboard-design-challenge)
[How to Ace the Dreaded Whiteboard Challenge](https://dscout.com/people-nerds/whiteboard-challenge-ux-research-interview-tips)
[Product Design Exercises We Use at WeWork Interviews](https://blog.prototypr.io/product-design-exercises-we-use-at-wework-interviews-2ee1f5a57319)
[Acing the Whiteboard Challenge](https://imprint.li/100days/index.php/whiteboard-challenges/)
[19 Whiteboard and Take-Home Design Challenges for UX Designers, UX Design Institute](https://www.uxdesigninstitute.com/blog/design-challenges-for-ux-designers/)

**Comment by pogwon** [comment]
### Instructions for the UX Whiteboard Challenge
 - Give Introduction for UX Whiteboard Challenge (What is it? Why do companies conduct it?) 
 - Provide the resource/notes on how to answer/respond to UX Whiteboard Challenges 
 - Provide 2 prompts for the UX Whiteboard Challenge. Members can choose to work on **_one_** of the prompts. Based on the domain they specialise in - example: UX Research, Design, Writing, Generalist etc. 
 - Allocate 20-minutes for members to complete their Whiteboard Challenge on the FigJam. The short time-frame is to emulate the time-sensitive real-world conditions of job interviews. 
 - Co-Leads will function as moderators/hiring managers. Members can choose to ask follow-up questions during the course of these 20-minutes as they work on their concepts during the Whiteboard Challenges. To emulate Job Interviews. 
 - Members can choose to write, draw, sketch, add pictures etc. on their FigJam to explain their concepts & solution derivation. 
 - Allocate 5-10 minutes to each member to present their solutions to the Whiteboard Challenge & for peer feedback from other community members.

**Comment by pogwon** [comment]
### Prompts for UX Whiteboard Challenge 

---------

1. **Stop unwanted subscription fees**

It’s hard to keep track of all the products and services that we have subscribed to every month. All we see is money deducting from our accounts, sometimes from services that we don’t need anymore. How can you design a product which helps manage subscriptions?

---------

2. **Car Locator**

Help our employees find their cars in the parking lot.
We have over 15,000 employees and all of their cars in our main campus. Employees have been “losing” their cars in the lot. They forget which of the 5 giant parking lots they parked in and are wandering around clicking their door alarms in order to find their cars. The noise pollution at the end of the day is terrible.
We already have a company app. We want to add a feature that will help employees find their cars.

Consider
- Couples often swap cars when driving to work. What if the employee has more than one car s/he drives to work?
- This feature should be prominent on the app–but the home screen is already full. How will you make it fit without removing something?

------

4. **Elevator Lobby**
Our elevators work great, however, with over 2500 people using our elevators every day, we need a better system to get everyone to the right one.
Consider
Redesign the lobby anyway you chose
How people mingle in the (smallish) lobby
People are in a hurry getting to work on time

-----

5. **When pets are home alone**
No matter how much we love our pets, we still need to leave home to go to work, travel, run errands … leaving our pets home alone and sad. How can you enable pet owners to interact with their pets when they’re not at home?

-----

**Comment by pogwon** [comment]
### Collaborative FigJam workspace

<img width="922" alt="Screenshot 2023-09-14 at 2 55 21 PM" src="https://github.com/hackforla/UI-UX/assets/129242704/cb9ea0b8-41a5-4fe6-9f8d-951c7b02bb1d">
<img width="304" alt="Screenshot 2023-09-14 at 2 55 36 PM" src="https://github.com/hackforla/UI-UX/assets/129242704/bfebf46c-2a63-44f0-8cd7-23cc0f25c534">
<img width="997" alt="Screenshot 2023-09-14 at 2 55 43 PM" src="https://github.com/hackforla/UI-UX/assets/129242704/2a7b6bef-7cca-4000-a84d-362defa54ea9">
<img width="919" alt="Screenshot 2023-09-14 at 2 55 52 PM" src="https://github.com/hackforla/UI-UX/assets/129242704/998dcdcb-3ab0-4a56-ab20-98b83ced4aac">
<img width="1188" alt="Screenshot 2023-09-14 at 2 56 00 PM" src="https://github.com/hackforla/UI-UX/assets/129242704/471b9373-f7de-4439-bb2a-3cf87879b860">
<img width="949" alt="Screenshot 2023-09-14 at 2 56 09 PM" src="https://github.com/hackforla/UI-UX/assets/129242704/16baa8b5-ee55-4e79-a5f1-5f9341e4fd6b">

**Comment by pogwon** [comment]
### Slack Call-outs/Announcements

https://hackforla.slack.com/archives/C017ESHSMNG/p1694556924308859

https://hackforla.slack.com/archives/C017ESHSMNG/p1694728488089049

**Comment by Aparna1Gopal** [comment]
### Notes
- [Wiki](https://github.com/hackforla/UI-UX/wiki/Workshop-Series) updated 
- This Issue is complete & is being closed
