### ISSUE TITLE
UI/UX CoP: 2024-05-16: Workshop: Your UX Journey with us!

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#573]
### Workshop Name
Workshop: Your UX Journey with us!
(Participatory Design: Feedback from UI/UX CoP members on goals for the community)

### Workshop Description
- This is a participatory design workshop conducted during the weekly UI/UX Community of Practice meeting.
- Goal of the workshop is to identify the goals for the community, by the peers & members in the community.
- This participatory design collaborative workshop will be conducted once every quarter to track the progress of the community. Based on the activities that were included as a result of conducting these participatory design collaborations. 
- This will also serve as a tracker for co-leads to identify the positives & negatives of any activities that were conducted. Future activities for the community can be iterated based on the community feedback. 

### Date and Time
May 15, 2024 - 6-7PM PST

### Target Audience
All members of the UI/UX Community of Practice 

### Action Items
- [x] Collate all relevant resources for this Issue, under Resources/Instructions
- [x] Identify relevant [goals](https://github.com/hackforla/UI-UX/issues/573#issuecomment-2112574050) for the UI/UX Community of Practice 
- [x] Design & create the [FigJam Workspace ](https://github.com/hackforla/UI-UX/issues/573#issuecomment-2112550493)
- [x] Share the issue with other UI/UX CoP Co-Leads to receive feedback 
- [x] Make any changes, if required, after review by Co-Leads 
- [x] On the day of CoP Meeting, [explain the activity](https://github.com/hackforla/UI-UX/issues/573#issuecomment-2112574814) to the attending members 
- [x] Share the link to the [FigJam Workspace](https://www.figma.com/board/boYOVROdfo5AEmb68R9D7G/%F0%9F%8E%A8FigJam-(UI%2FUX-CoP)%F0%9F%8E%A8?node-id=689-4360&t=depc1zA975wvBx6O-4)
- [x] Once activity is complete, take screenshot of FigJam activity and record it in this issue 
- [x] Analyse the data from the workshop using FigJam AI 
- [x] Identify the common trends, expectations & goals from the community members 
- [x] Take screenshot of the results & findings and record it in this issue
- [x] Share the results & findings with Co-leads during the monthly UI/UX CoP Co-Leads meeting (beginning of next month) 
- [x] Use these results & findings to plan the activities for the next month 
- [ ] Review with Co-Leads & close issue

### Instructions
[Instructions to use the FigJam Workspace](https://github.com/hackforla/UI-UX/issues/573#issuecomment-2112574814)

### Resources
[Participatory Design: Feedback from UI/UX CoP members on goals for the community - JANUARY 2024](https://github.com/hackforla/UI-UX/issues/544)
[60+ Feedback Questions to Improve Your Product and Increase Customer Satisfaction](https://userpilot.com/blog/feedback-questions/)
[28 of our favorite customer feedback questions](https://www.hotjar.com/blog/customer-feedback-questions/)
[50 Powerful User Interview Questions You Should Consider Asking](https://blog.respondent.io/best-user-interview-question)
[13 Open-Ended Customer Interview Questions for Product Managers](https://www.uservoice.com/blog/open-ended-questions)

### Agenda
[Agenda May 15, 2024](https://github.com/hackforla/UI-UX/issues/540#issuecomment-2112539903)

### Facilitator(s)
Primary Facilitator
- [x] Aparna G (UI/UX Co-lead)

Additional Facilitators 
- [x] Julia G (UI/UX Co-lead) 
- [ ] Peter G (UI/UX Co-lead)

### Workshop Message and call-out
https://github.com/hackforla/UI-UX/issues/573#issuecomment-2113899776

### Feedback Summary
https://github.com/hackforla/UI-UX/issues/573#issuecomment-2113896274

### Next Steps
- Analyse the results from the collected feedback 
- Share results with Co-leads during planning meeting

**Comment by Aparna1Gopal** [comment]
### [FigJam Workspace](https://www.figma.com/board/boYOVROdfo5AEmb68R9D7G/%F0%9F%8E%A8FigJam-(UI%2FUX-CoP)%F0%9F%8E%A8?node-id=689-4360&t=depc1zA975wvBx6O-4)

**Comment by Aparna1Gopal** [comment]
### Goals for the UI/UX Community of Practice

Primary Goal
- What types of activities will enhance the user experience of the community members? 
- What are the existing activities that can be retained and what can be introduced new? 


**Participatory Design: WORKSHOP GUIDE**
Participatory Design: Feedback from UI/UX CoP members on goals for the community - JANUARY 2024


UI/UX Community of Practice 

Hello! 👋 

STEP 1
About You! 

When did you Onboard at Hack for LA (Month/Year)? 

Your target or dream role?

Any adjacent roles you are open to?

Skills you already possess (technical/non-technical)? 

Skills you would like to improve on (technical/non-technical)? 

For new member goto STEP 2
Our returning member goto STEP 3

STEP 2
Our new members: 
You are a part of our peer community now! 

What training/benefits/experiences/activities would help you improve your skills? 

STEP 3 
Our returning community members! 

What keeps you coming back to our community? 

What skills gained from this community has helped you in your career goals? 

What would you like to see more of, in this community? Any training/benefits/experiences/activities? 

STEP 4
Use a sticker to describe your mood right now!

**Comment by Aparna1Gopal** [comment]
### Instructions to use the FigJam Workspace 

- Read the questions in each Step 
- There are 4 Steps 
- Take a post-it from the tools section of the FigJam workspace (located in the bottom) and start answering! 
- Take a separate post it to respond to each step (Steps 1-4)
- Take 15-20 minutes to complete activity (Use background music on FigJam to keep the activity entertaining) 
- Once activity is complete, use 10-15 minutes requesting members to discuss their stickers chosen for the day "Use a sticker to describe your mood right now!" Why did they choose what they did? (This can function as a fun activity in the midst of all the brainstorming/thinking during the FigJam activity)

**Comment by Aparna1Gopal** [comment]
### FigJam Activity conducted on May 15, 2024

<img width="1204" alt="Screenshot 2024-05-16 at 7 55 20 AM" src="https://github.com/hackforla/UI-UX/assets/86335455/5cde92de-fb66-4f1f-890d-a166935dd2b1">

**Comment by Aparna1Gopal** [comment]
### Slack Communication 

<img width="1063" alt="Screenshot 2024-05-16 at 7 58 22 AM" src="https://github.com/hackforla/UI-UX/assets/86335455/35553650-a05e-4b8f-a858-9f1a9ed5ad6f">

**Comment by Aparna1Gopal** [comment]
### Impact of conducting workshop

- Discussed results with the Co-Leads during next planning meeting (June 2024). 
- Planning activities for the UI/UX CoP. 
- Based on feedback received, the UI Design Workshop planned for June 12, 2024 had some items implemented from this workshop. Community members requested for more training on Figma use. The UI Design Worksop (Digital Illustration) will be conducted using Figma. Such that community members have better practice with Figma. This recorded workshop will also made available as a training video on the UI/UX CoP's YouTube channel. 
- Discuss all the results from the workshop during July 2024 planning meeting as well, to plan ideas & activities for August & September 2024.

**Comment by Aparna1Gopal** [comment]
<img width="1112" height="2692" alt="Image" src="https://github.com/user-attachments/assets/8cf71f94-5b82-44f5-9480-bb0beafeaf94" />
