### ISSUE TITLE
Project board migration prep

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/UI-UX#576]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
- [x]  copy this template to a comment below
   ````
   ### Text from project board card
   ```
   [INSERT MARKDOWN HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [x] copy markdown from a card in the "Start Here" column of the Project Board into your new comment where it says `[INSERT MARKDOWN HERE]
- [x] delete card from project board.

### Resources/Instructions
Project board URL:

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card
```
**Guide**

Please read this guide https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?usp=sharing to learn how to create your UX Experience Profile
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Main board, Start Here column
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Main board, Start Here column
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Main board, Start Here column
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Main board, Icebox column
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Main board, Icebox column
```
**Project Name**: UI/UX Community of Practice

**About the Project**: Host weekly meetings, onboard new joiners, arrange talks, organize workshops, and guide new volunteers in their journey at Hack for LA and through their career development in UI/UX Design, Research, Writing and/or ResearchOps. Check out more info under Resources.

**Volunteer Opportunity**: Co-Lead

**Duration**: Ongoing

**Meetings**: 
- Wed, 6-7pm PST (UI/UX CoP meeting)
- Wed, 7-7:30pm PST (CoP co-leads meeting)

**Who to communicate your interest to**
- Slack channel link: [#UI/UX](https://hackforla.slack.com/archives/C017ESHSMNG)
- Slack name of person to contact in the channel:
    - **Julia Gab**
    - **Aparna Gopal**
    - **Jennifer Nguyen**

**Resources:** 
https://github.com/hackforla/UI-UX
https://github.com/hackforla/UI-UX/wiki
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Main Board, Questions/Review
```
Add issues pertaining to questions or issues that require CoP Lead review to this column
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, InHouse CoP projects
```
Agenda & Planning for in-house UI/UX CoP projects
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, InHouse CoP projects
```
Add issues pertaining to questions or issues that require CoP Leads to review to this column
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
Description of In house project board view: Projects incubated within the UI/UX Community of Practice

**Comment by pogwon** [comment]
### Text from project board card: UI/UX Research Open Roles: Instructions Column
```
# START HERE
We know this board is ugly!!!

- [Find a volunteer Opportunity](https://github.com/hackforla/UI-UX/projects/2#card-53063747)
- [Post a volunteer Opportunity](https://github.com/hackforla/UI-UX/projects/2#card-87993814)
- [Remove a volunteer Opportunity](https://github.com/hackforla/UI-UX/projects/2#card-53065904)

If you know some places where we should post these opportunities please [submit UX channels](https://docs.google.com/forms/d/e/1FAIpQLSfB7lBSeYMhN8EBS46qdAVnd7N5Ocx5lPEwEvu9Gfl7bLbACA/viewform) after you check to make sure its not on the list of  [existing UI/UX channels we know about](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/preview)

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card: UI/UX Research Open Roles: UX Research Program Design Manager Column
```
#### UX Program Designers Role
This role is for experienced program designers.  You will likely be creating a program that interfaces with the identified stakeholders and their communities.  You will not have to manage the team if you do not want to, your role will be to design the surveys and co-create a training to teach junior UX Researchers how to conduct it.
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card: UI/UX Research Open Roles: UI/UX Community of Practice Co-Lead Column
```
**Project Name**: UI/UX Community of Practice

**About the Project**: Host weekly meetings, onboard new joiners, arrange talks, organize workshops, and guide new volunteers in their journey at Hack for LA and through their career development in UI/UX Design, Research, Writing and/or ResearchOps. Check out more info under Resources.

**Volunteer Opportunity**: Co-Lead

**Duration**: Ongoing
Minimum 3-6 months commitment

**Meetings**: 
[Meeting times](https://github.com/hackforla/UI-UX/wiki/CoP-Leads#meeting-times)

**Who to communicate your interest to**
- Slack channel link: [#UI/UX](https://hackforla.slack.com/archives/C017ESHSMNG)
- Slack name of person to contact in the channel: [UI/UX CoP Co-leads on the Current Team](https://github.com/hackforla/UI-UX/wiki/CoP-Leads#current-team) 

**Resources**
UI/UX CoP's [Wiki](https://github.com/hackforla/UI-UX/wiki) & [README](https://github.com/hackforla/UI-UX/commit/2ad4f8c44de41272b0dec9c96c673dab36077c99)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by pogwon** [comment]
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, Design Lead column
```
#### Design Lead
Design Leads work on strategy and are people leaders as well and producing great looking imagery
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, UX/Product Designer column
```
#### UX/Product Designer
Do you believe the user should always be at the center of product design? Do you have a knack for interviewing and talking to users to identify their needs? If you answered yes then HfLA wants to talk to you! As a UX designer, you will have the opportunity to collaborate on identifying and ideating on the user journey, identifying pain-points and potential gain points, in order to build a world-class experience for a Hack for LA product. [Read more](https://github.com/hackforla/civic-opportunity/blob/master/roles-1/ux-designer.md)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, Filled column
```
#### These are volunteer opportunities that are now filled.
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, UI/Visual Designer column
```
#### UI/Visual Designer
The UI designer collaborates on defining the look and feel of the product, visualizing, and creating graphics including illustrations and layouts. You’ll be the one to shape the visual aspects of the website, product materials, exhibitions, and more. Your graphics should capture the attention of those who see them and communicate the right message. [Read more](https://github.com/hackforla/civic-opportunity/blob/master/roles-1/ui-designer.md)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, Instructions column

```
# START HERE
We know this board is ugly!!!

- [Find a volunteer Opportunity](https://github.com/hackforla/UI-UX/projects/3#card-53874287)
- [Post a volunteer Opportunity](https://github.com/hackforla/UI-UX/projects/3#card-53874282)
- [Remove a volunteer Opportunity](https://github.com/hackforla/UI-UX/projects/3#card-53874266)

If you know some places where we should post these opportunities please [submit UX channels](https://docs.google.com/forms/d/e/1FAIpQLSfB7lBSeYMhN8EBS46qdAVnd7N5Ocx5lPEwEvu9Gfl7bLbACA/viewform) after you check to make sure its not on the list of  [existing UI/UX channels we know about](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/preview)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, Instructions column

```
#### Post a Volunteer Opportunity
---
Steps:
1. Get added to this board (reach out to Olivia or Bonnie to be added)
1. click on the plus sign at the top of the column to start a new card under the role type your project falls under
1. If the role type dosen't exist, please make a new column and add a description ([they can be found here](https://github.com/hackforla/civic-opportunity/tree/master/roles-1))
1. Use the following format (the character limit is 1024):

**Project Name**: [your project name replaces these brackets]

**About the Project**: [your brief description replaces these brackets]

**Volunteer Opportunity**: [your opportunity description replaces these brackets]

**Duration**: 

**Who to communicate your interest to**
- Slack channel link: #
- Slack name of person to contact in the channel

[Read more about the project]([your project home page on hackforla.org website goes here])

**Resources:**
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, Instructions column

```
#### Find a volunteer opportunity
---

**Steps**
1. [Signup for the Hack for LA Slack Workspace](http://hackforla.org/slack)
1. If you don't already have a GitHub account, please [signup](https://github.com).  We use boards like this to organize information quickly.
1. Read the role descriptions at the top of the columns, pick which is appropriate for your existing skill level
1. Read through the opportunities posted by the teams, pick one and communicate with the team by following the instructions on the opportunity cards.
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Design Open Roles project board card, Instructions column

```
#### Remove a Volunteer Opportunity
---

**Steps**
1. Confirm that you are the UX or PM lead for your project and that your PM(s) wants this opportunity removed.
1. Edit the opportunity by click the three dots ... on the top right corner of the card.
1. Add  ~~ at the top and the bottom of the card (eg. ~~strike this text out~~)
1. Move to the filled column
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Open Roles project board card, UX Research Team Leads
```
#### UX Research Team Lead
This role needs to be filled by someone who has a lot of time to devote to recruiting,  training and managing the UX Researchers for the research your team is about to conduct.  You will not have to create the training, but you are welcome to participate in its creation.
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from UI/UX Open Roles project board card, UX Research Program Design Manager
```
#### UX Program Designers Role
This role is for experienced program designers.  You will likely be creating a program that interfaces with the identified stakeholders and their communities.  You will not have to manage the team if you do not want to, your role will be to design the surveys and co-create a training to teach junior UX Researchers how to conduct it.
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
The Guides team backed up all the cards on the guides and templates board in this issue https://github.com/hackforla/guides/issues/172

**Comment by Aparna1Gopal** [comment]
This issue is complete and being closed
