### ISSUE TITLE
UI/UX CoP Meeting Agenda 2025 (Wednesday 6PM PT)

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#596]
### Overview
This issue tracks the agenda for the weekly UI/UX CoP meetings.

### Weekly Agenda, Recordings, and Meeting Notes
- [January 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-2580304254)
- [February 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-2655274385)
- [March 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-2719490115)
- [April 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-2811530341) - UI/UX CoP on hiatus due to TDM-Calculator all-team collaboration 
- [May 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-2883139170)
- [June 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-2965159161)
- July 2025 - UI/UX Community of Practice on Summer Break
- [August 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-3186567986)
- [September 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-3303075723)
- [October 2025](https://github.com/hackforla/UI-UX/issues/596#issuecomment-3379359903)
- [November 2025]()

### Resources/Instructions

- [Zoom link for Wednesday meetings](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09)
- [Google Drive UI/UX CoP folder](https://drive.google.com/drive/folders/1Bw4qy9rQtJ16ccYsRUIg5BlxBxlqnEIQ?usp=sharing)
- [2024 UI/UX CoP Agenda Issue](https://github.com/hackforla/UI-UX/issues/540)
- [UI/UX Cop Lead / Org Agenda](https://github.com/hackforla/UI-UX/issues/187)

#### Template for Slack Channel Announcements - TEMPLATE 1 
<details>
<summary>Slack channel template - Replace emojis and info as needed</summary>
:sparkle: **This Week's UI/UX Community of Practice!** :sparkle:

:bulb:**What?** [REPLACE]
:watch:**When?** [REPLACE]
:computer:**Where?** [REPLACE]
:trophy:**Why?** [REPLACE]

:meow_bread_appear: **Need the Zoom link?** If you have been onboarded to Hack for LA already, please use this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09) to attend our UI/UX CoP weekly meetings.  If you have questions, message us in the UI/UX Slack Channel. 
UI/UX CoP Leads (add details from Wiki) 

</details>

#### Template for Slack Channel Announcements - TEMPLATE 2 
<details>
<summary>Slack channel template - Replace emojis and info as needed</summary>

Hi UI/UX Community! Join us for our weekly Community of Practice meeting on Wednesday (DATE) at 6PM PT. Join us using this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09). 
:mega: Topic: (ADD TOPIC OF THE WEEK HERE)

:meow_bread_appear: **Need the Zoom link?** If you have been onboarded to Hack for LA already, please use this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09) to attend our UI/UX CoP weekly meetings.  If you have questions, message us in the UI/UX Slack Channel (add Slack channel details here). 
UI/UX CoP Leads (add details from Wiki) 

</details>

</details>

#### Template for Slack Channel Announcements - TEMPLATE 3 
<details>
<summary>Slack channel template - Replace emojis and info as needed</summary>

:spiral_calendar_pad: Hi Community! No UI/UX CoP Meeting this Wednesday (due to planning week during the first week of the month).
:virtual-meeting: Meet you next Wednesday [DATE] at 6PM PT for the Community Meetup! Join us using this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09). 

:dart: We will be covering the following topics & discussions during the **Community Meetup**  :hfla-logo-2: So bring your questions/portfolios/resumes for peer review and feedback! 
- Portfolio & Resume Reviews
- Design Critique & Feedback
- Interview Practice (Technical and Soft Skills)
- Networking with other UX Professionals
- Post-Onboarding Support

:handshake: **Need the Zoom link?** If you have been onboarded to Hack for LA already, please use this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09) to attend our UI/UX CoP weekly meetings. If you have any questions, please message us in this UI/UX Slack Channel (add Slack channel details here) - CC: UI/UX CoP Leads (add details from Wiki) 

</details>

#### Template for Slack Channel Announcements - TEMPLATE 4 - THANK YOU MESSAGE 
<details>
<summary>Slack channel template - Replace emojis and info as needed</summary>

Thank You All for joining us tonight for the discussion on [ADD TITLE OF MEETUP/WORKSHOP] :dart::memo::chart_with_upwards_trend:[ All resources from the meeting can be found here][Add resources here]. Special thanks to [at ADD NAME, at ADD NAME] for their contributions! All the best in your [ADD MEETUP NAME/WORKSHOP TITLE] :sparkles::laptop_parrot: - CC: [UI/UX CoP Leads](https://github.com/hackforla/UI-UX/wiki/CoP-Leads#current-team)

(OR) 

Hi UI/UX Community!:blob-wave:
:virtual-meeting:  Thank you for joining us at the Community Meetup last week. Special thanks to [at NAME][at NAME] for their contributions!
:books: Some great resources on [ADD RESOURCES]
:hfla-logo-2: This week, join us for our weekly Community of Practice meeting on Wednesday [DATE] at 6PM PT. Join us using this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09).
:mega: Topic: Case Study Presentations/Walkthroughs :female-technologist::skin-tone-2::blue_book::memo:
:handshake: Need the Zoom link? If you have been onboarded to Hack for LA already, please use this [Zoom Registration Link](https://us06web.zoom.us/j/89597380276?pwd=TWFxajJmMnd1YXBBM05GSHNYdElSQT09) to attend our UI/UX CoP weekly meetings. If you have questions, message us in the [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG) - [UI/UX CoP Leads](https://github.com/hackforla/UI-UX/wiki/CoP-Leads#current-team)

</details>

#### Template for Meeting Agenda
Copy and paste code below:
```

## YYYY-MM-DD Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)
```

**Comment by Aparna1Gopal** [comment]
## 2025-01-08 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items
- Welcome Back! 🙌 
- Office hours and post-onboarding support 
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda
- Office hours 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-01-15 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Office hours and post-onboarding support
 
### Notes from meeting
- New member N Deng (who onboarded in late November) attended and required post-onboarding support. Reviewed all permissions (Onboarding FigJam, Github, UI/UX Slack channels, UI/UX CoP Google drive). Provided info on all open roles based on their interests & background and skills they are looking to develop. 
- Posted post-onboarding message in the Slack channel with all relevant information and pinned the updated January 2025 message to the channel for easy access. 


### Tasks
- Co-ordinate with Co-Leads to review the existing January & February schedule and make necessary edits/changes as required, due to change in existing schedule

### Items for next week's agenda
- Office hours & post Onboarding support

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-01-22 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Office Hours & post-Onboarding support
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda
- https://github.com/hackforla/UI-UX/issues/597


<img width="970" alt="Image" src="https://github.com/user-attachments/assets/a3b4968b-3a68-4f75-a91a-0a83a4a5642f" />

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by pogwon** [comment]
## 2025-01-29 Meeting Agenda
 
### Prework to prep for meeting
- Re-using [meeting format from November, 12, 2024](https://github.com/hackforla/UI-UX/issues/540#issuecomment-2472454118), since we didn't get to use this format back then.
- Format & Schedule for Interview Prep:
   - 6:00 - 6:10: Office Hours/Answer any questions members have
   - 6:10 - 6:15: Introduction to meeting and explanation of process
   - 6:15 - 6:30: Brainstorming session for participants. Each person will pick two questions to answer and can use this time to prepare their answers
   - 6:30 - 6:55: Interview prep session with feedback*
   - 6:55 - 7:00: Wrap up
 
### FYIs (nothing needs to be done, just keeping each other informed)
Format for this meeting will depend on how many people attend:
- If there are over eight participants, we should divide into pairs and assign breakout rooms for each pair. Each five-minute session will have one person answering and the other giving feedback before switching rooms. If there is an odd number of participants, one co-lead can participate.
- If there are under eight participants, we will have a group interview style where one person is given 2-5 minutes (depending on how many people are present) to answer followed by brief feedback. Everyone will go once before circling around so each person has had a chance to answer.

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
Resources
- UX Design Interview Questions
    - https://www.springboard.com/blog/design/ux-design-interview-questions/
    - https://www.coursera.org/articles/ux-designer-interview-questions-and-answers
    - https://www.linkedin.com/pulse/15-essential-uiux-designer-interview-questions-answers-sachin-mittal-tlusc/
    - https://www.nngroup.com/articles/answer-ux-job-interview-questions/
    - https://bootcamp.umass.edu/blog/ui-ux/essential-ux-designer-interview-questions-and-answers-for-2023
    - https://resources.workable.com/designer-interview-questions
    - https://docs.google.com/spreadsheets/d/1GdMO9i87LB6vec2Hgx844Y72akfQGNOIMFoIcpzF9p8/edit?gid=1037361934#gid=1037361934
 - UX Research Interview Questions
    - https://www.linkedin.com/feed/update/urn:li:activity:7064662703688011776/?updateEntityUrn=urn:li:fs_feedUpdate:(V2,urn:li:activity:7064662703688011776)
    - https://docs.google.com/spreadsheets/d/1GdMO9i87LB6vec2Hgx844Y72akfQGNOIMFoIcpzF9p8/edit?trk=public_post_comment-text&gid=274855658#gid=274855658
    - https://medium.com/@eleonorazucconi/46-interview-questions-for-user-experience-researchers-at-google-amazon-microsoft-and-facebook-c582827267b9
      
- Interview Practice Tool - [Google Interview Warmup](https://grow.google/certificates/interview-warmup/)
 
### Notes from meeting


### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by pogwon** [comment]
## 2025-02-19 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Fireside Chat: What else can you do with a UX background? Let's chat about UX adjacent careers! 🎯
 
### Notes from meeting



### Tasks
- Schedule Slack meeting reminder for next week with specific title of event/activity planned 


### Items for next week's agenda


---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-02-19 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-03-19 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Office Hours 
 
### Notes from meeting
- Open Office hours 
- No member turn-out. UI/UX CoP Co-Leads worked on admin items for the CoP.


### Tasks
 

### Items for next week's agenda
- Schedule Slack meeting reminder for next week with specific title of event/activity planned
- Prep items for discussion for next week's activity 
- Re-post open role recruitment for UI/UX CoP Co-Lead 

<img width="986" alt="Image" src="https://github.com/user-attachments/assets/bfc292a0-c2e7-41b4-838c-77daef891632" />

<img width="983" alt="Image" src="https://github.com/user-attachments/assets/faeb839d-a362-42d5-83f3-20abda5ced94" />


---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-03-26 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Workshop: Best Practices - Presenting Case Studies during Job Interviews 📔
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda
- No meeting next week. Planning week. 

<img width="983" alt="Image" src="https://github.com/user-attachments/assets/e0b05ffe-b2d0-469d-8ecb-ece90d15f12f" />

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-04-16 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Office Hours & Post- Onboarding Support 
 
### Notes from meeting
- 2 new members joined. Walked them through the post onboarding steps, including joining UIUX Slack channel, Open roles, Updated Experience Profile (mini-user testing to assess if the updated Experience Profile worked efficiently). To add a step under UI/UX CoP Board - Status in Experience Profile. 


### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-04-30 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- Office Hours - Post-Onboarding Support 
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/540)

**Comment by Aparna1Gopal** [comment]
## 2025-05-14 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

**Comment by Aparna1Gopal** [comment]
## 2025-05-21 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

**Comment by Aparna1Gopal** [comment]
## 2025-06-12 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 
- No UI/UX CoP Meeting this week 
 
### Notes from meeting

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/d1479486-04ef-4837-97bf-f3cbaf3d54bc" />


### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

**Comment by Aparna1Gopal** [comment]
## 2025-06-25 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Research Profile](https://github.com/hackforla/UI-UX/projects/5)
 - [ ] [UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2)
 - [ ] [UI/UX Design Open Roles](https://github.com/hackforla/UI-UX/projects/3)
 - [ ] [UI/UX Writing Open Roles](https://github.com/hackforla/UI-UX/projects/7)
 - [ ] [UI/UX Templates and Guides](https://github.com/hackforla/UI-UX/projects/1)


### New Items 

 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

<img width="973" alt="Image" src="https://github.com/user-attachments/assets/45bfccab-7416-41b6-ac6b-66212f24878b" />

**Comment by Aparna1Gopal** [comment]
## 2025-08-13 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 
- 
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

**Comment by Aparna1Gopal** [comment]
## 2025-09-10 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 
- Community Meetup 
 
### Notes from meeting
- 3 members joined. 
- 1 member presented their portfolio for community feedback. 
- 2 members required post-onboarding assistance and helped them with the same by walking-through the open role and identifying the best fit for them based on their experience, interests & time availability 


### Tasks
 

### Items for next week's agenda
- Case Study walk-through workshop. 
- Slack announcement regarding workshop. 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

<img width="979" height="418" alt="Image" src="https://github.com/user-attachments/assets/404ddbb2-6c40-4718-a90b-236187560f27" />

**Comment by Aparna1Gopal** [comment]
## 2025-09-17 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 
- Case Study Presentations/Walkthroughs 
 
### Notes from meeting
- Peter G presented case study of 311-data project 
- Members gave feedback on the case study. Emulated real-world job interview scenario with follow-up questions on the case study 


### Tasks
 

### Items for next week's agenda
- Community Meetup - Slack Announcement 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

<img width="975" height="437" alt="Image" src="https://github.com/user-attachments/assets/9219235b-5b7a-4755-a77f-9518f3445be6" />

<img width="962" height="346" alt="Image" src="https://github.com/user-attachments/assets/418116e9-bf1e-45fa-9165-b05a975c2583" />

**Comment by Aparna1Gopal** [comment]
## 2025-09-24 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 
- Community Meetup - Post Slack Message

 
### Notes from meeting
- Community member had pitched a Design Crit idea to the Co-Leads. Since the member stopped by the Community Meetup, the Co-Leads brainstormed with this community member to structure their pitch and workshop. 
- The Case Study Presentation by the community member is scheduled for October 29. All details will be documented in a Workshop issue template. 


### Tasks
 

### Items for next week's agenda
- Weekly announcement regarding the Planning Meeting (first week of the month) and Community Meetup for the next week after next. 

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

<img width="995" height="478" alt="Image" src="https://github.com/user-attachments/assets/85a2cd29-cb89-4a12-97dc-7143a86171be" />

**Comment by Aparna1Gopal** [comment]
## 2025-10-08 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 
- Community Meetup 
 
### Notes from meeting



### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

**Comment by Aparna1Gopal** [comment]
## 2025-11-12 Meeting Agenda
 
### Prework to prep for meeting
N/A
 
### FYIs (nothing needs to be done, just keeping each other informed)
N/A

### Recurring items: 
 - [ ] [Getting Started at HfLA UI/UX](https://github.com/hackforla/UI-UX)
 - [ ] [Set up Experience Profile](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit?slide=id.p#slide=id.p)
 - [ ] [UI/UX Content Open Roles](https://github.com/orgs/hackforla/projects/67/views/9)
 - [ ] [UI/UX Design Open Roles](https://github.com/orgs/hackforla/projects/67/views/4)
 - [ ] [UI/UX Research Open Roles](https://github.com/orgs/hackforla/projects/67/views/8)


### New Items 
- Community Meetup 👥📍🙌
- https://github.com/hackforla/UI-UX/issues/636#issuecomment-3524802547
 
### Notes from meeting


### Tasks
 

### Items for next week's agenda

---
[Link back to top of issue](https://github.com/hackforla/UI-UX/issues/596)

**Comment by Rabia2219** [comment]
- https://github.com/hackforla/UI-UX/issues/646
