### ISSUE TITLE
Guide: How and why to Use "Inspect Element" Features in Browser

### ISSUE THREAD

**Issue by daniellex0** [hackforla/UI-UX#99]
### Overview
We need to create a guide for the Inspect Element feature in browsers so that designers know the benefits of using it.

### Action Items
- [x] Gather examples of how other Hack for LA projects or volunteers have done this (if applicable), adding each example as a link in the resources section below
   - [x] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Research" label
- [x] Research existing information about [name of item] in [relevant resources, articles, etc.]
   - [x] Once done, remove the "Guide: Research" label and add the "Guide: Draft Guide" label
- [ ] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive](https://drive.google.com/drive/u/1/folders/1os-4KyGnL0SXIeyfoDICOEpG5CO_1MaV)
    - [ ] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Needs Peer Review" label
- [ ] Review the guide with UX/UI community of practice
   - [ ] Once done, remove the "Guide: Needs Peer Review" label and add the "Guide: Leadership Review" label
- [ ] Present to the Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Ready Publication" label

### Resources
Update issue #15 with the name of item you are working on
[Research](https://docs.google.com/document/d/1hasxayHUu1WV-vI-JxxxON47D6Y7FmdqQIsKIGNji9Q/edit)

#### Projects to check
- [100 Automations](https://github.com/100automations/website)
- [311 Data](https://github.com/hackforla/311-data)
- [Access the Data](https://github.com/hackforla/access-the-data)
- [BallotNav](https://github.com/hackforla/ballotnav)
- [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
- [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend)
- [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
- [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
- [Data Science Projects](https://github.com/hackforla/data-science)
- [Design Systems](https://github.com/hackforla/design-systems)
- [Engage](https://github.com/hackla-engage)
- [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
- [Food Oasis](https://github.com/hackforla/food-oasis)
- [GreenEarthOS](https://github.com/hackforla/climate-project)
- [Guides](https://github.com/hackforla/guides) 
- [HomeUniteUs](https://github.com/hackforla/homeuniteus)
- [Internship project](https://github.com/hackforla/intership)
- [Lucky Parking](https://github.com/hackforla/lucky-parking)
- [Open Community Survey](https://github.com/hackforla/open-community-survey)
- [TDM Calculator](https://github.com/hackforla/tdm-calculator)
- [VRMS](https://github.com/hackforla/vrms)
- [Hack for LA's Website](https://github.com/hackforla/website)
- [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/)

**Comment by anonymousanemone** [comment]
Summer internship ended and had to prioritize school work.
Research has been completed and a rough outline is available in the "Research" link google folder.

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by NilakshiS** [comment]
1. Progress: Task is still in progress, currently at the gathering examples with GitHub stage.
- Completed: Checked projects from 100 Automations to Expunge Assist in the list for examples of using inspect element, skipping projects that are on hold.
- Left: Checking projects from Food Oasis to Youth Justice Nav in the list

2. Blockers: None

3. Availability: I will have 5-6 hours this week to work on this issue.

4. ETA: It would take me about 2 weeks to complete the gathering examples with GitHub stage.

**Comment by NilakshiS** [comment]
Unassigning myself because I cannot finish this issue, I'm currently occupied with a different project. No more progress on the issue since what was last reported.

For reference, to find the issues listed, I searched the following terms in issues and checked the closed as well as open issues: “inspect”, “inspect element”, “devtools”, “chrome devtools”, “chrome inspect”.

**Comment by JesseTheCleric** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Overview
We need to create a guide for the Inspect Element feature in browsers so that designers know the benefits of using it.

### Action Items
- [x] Gather examples of how other Hack for LA projects or volunteers have done this (if applicable), adding each example as a link in the resources section below
   - [x] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Research" label
- [x] Research existing information about [name of item] in [relevant resources, articles, etc.]
   - [x] Once done, remove the "Guide: Research" label and add the "Guide: Draft Guide" label
- [ ] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive](https://drive.google.com/drive/u/1/folders/1os-4KyGnL0SXIeyfoDICOEpG5CO_1MaV)
    - [ ] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Needs Peer Review" label
- [ ] Review the guide with UX/UI community of practice
   - [ ] Once done, remove the "Guide: Needs Peer Review" label and add the "Guide: Leadership Review" label
- [ ] Present to the Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Ready Publication" label

### Resources
Update issue #15 with the name of item you are working on
[Research](https://docs.google.com/document/d/1hasxayHUu1WV-vI-JxxxON47D6Y7FmdqQIsKIGNji9Q/edit)

### Tasks
- [ ] **Gathering Examples with GitHub**
Follow the instructions from the slide deck Part 1: [Gathering Examples With GitHub: Wiki, Issues, Project Board, Resources Provided](https://docs.google.com/presentation/d/1XWY-OMiomzpKw_aCL1JkdgAhqpgGDZ2bu_XuReTO1zw/edit#slide=id.g150e30fd48b_0_443)
  - Remove the following labels from your issue as you complete them:
     - [ ] status: needs wiki examples
     - [ ] status: needs issues examples
     - [ ] status: needs project board examples
  - Congrats you have completed Part 1: Gathering Examples With GitHub: Wiki, Issues, Project Board, Resources Provided
     - [ ] Go to [Gather Examples, Use GitHub Search](https://github.com/hackforla/guides/wiki/Gathering-Examples-with-Github-Search) and copy the the text block (next steps), below this line

#### Projects to check
- [100 Automations](https://github.com/100automations/website) - on hold
- [311 Data](https://github.com/hackforla/311-data)
   - wiki examples: none
   - issues examples: 
   - project board examples: none
- [Access the Data](https://github.com/hackforla/access-the-data)
   - wiki examples: none
   - issues examples: none
   - project board examples: none
- [BallotNav](https://github.com/hackforla/ballotnav) - on hold
- [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
   - wiki examples: none
   - issues examples: none
   - project board examples: none 
- [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend) - on hold
- [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
   - wiki examples: none
   - issues examples: none
   - project board examples: none 
- [Design Systems](https://github.com/hackforla/design-systems) - on hold
- [Engage](https://github.com/hackla-engage) - on hold
- [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
   - wiki examples: none
   - issues examples: 
      - https://github.com/hackforla/expunge-assist/issues/823#issue-1586993574
         - https://github.com/hackforla/expunge-assist/issues/825#issue-1587004200
      - https://github.com/hackforla/expunge-assist/issues/717#issue-1412382458
         - https://github.com/hackforla/expunge-assist/issues/717#issuecomment-1281642635
         - https://github.com/hackforla/expunge-assist/issues/717#issuecomment-1329938186
   - project board examples: none
- [Food Oasis](https://github.com/hackforla/food-oasis)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [GreenEarthOS](https://github.com/hackforla/climate-project) - on hold
- [Guides](https://github.com/hackforla/guides) 
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [HomeUniteUs](https://github.com/hackforla/homeuniteus)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [Tech Work Experience (Internship project)](https://github.com/hackforla/internship)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [Lucky Parking](https://github.com/hackforla/lucky-parking)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [Open Community Survey](https://github.com/hackforla/open-community-survey) - on hold
- [People Depot](https://github.com/hackforla/peopledepot)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [Tables team](https://github.com/hackforla/tables/)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [TDM Calculator](https://github.com/hackforla/tdm-calculator)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [VRMS](https://github.com/hackforla/vrms)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [Hack for LA's Website](https://github.com/hackforla/website)
   - wiki examples: 
   - issues examples: 
   - project board examples: 
- [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/) - on hold

### Communities of Practice
- [Data Science Projects](https://github.com/hackforla/data-science)
- [UI/UX](https://github.com/hackforla/UI-UX)
- [Dev Ops](https://github.com/hackforla/ops)
- [Product](https://github.com/hackforla/product-management)
- [Engineering](https://github.com/hackforla/engineering)

<p>
<details>

**Comment by JesseTheCleric** [comment]
<details><summary>Prior version of issue</summary>
<p>

<img width="166" alt="image" src="https://github.com/user-attachments/assets/1200df27-963d-4e04-846a-56c0a42e50ad">
<p>
<details>
